# STEP 17 — FEATURE ENGINEERING

This notebook continues from the officially locked Week 2 cleaned dataset.

The feature engineering process will create controlled analytical features while preserving the cleaned source dataset structure and original source columns.

The objectives of this step are to:

- Create delivery and transit-related analytical features
- Create delay and operational performance indicators
- Create date-derived analytical features
- Create approved logistics and route-related indicators
- Preserve all original source columns
- Validate engineered feature logic mathematically
- Verify row and column integrity after each implementation stage

The uploaded Week 2 cleaned dataset will be treated as the baseline source for all feature engineering activities.

No original source column will be overwritten or removed unless explicitly approved and validated.

In [17]:
# STEP 17.1A — FEATURE ENGINEERING DATASET LOADING & BASELINE SETUP

import pandas as pd
import numpy as np

file_name = "Logistic_Data_Analyst_Cleaned_Week2.csv"

df = pd.read_csv(
    file_name,
    low_memory=False
)

expected_rows = 180519
expected_columns = 55

print("STEP 17.1A — FEATURE ENGINEERING DATASET LOADING & BASELINE SETUP")
print("=" * 80)

print("\nDATASET LOAD STATUS")
print("-" * 80)
print(f"Dataset File: {file_name}")
print(f"Current Dataset Rows: {df.shape[0]}")
print(f"Current Dataset Columns: {df.shape[1]}")

print("\nBASELINE STRUCTURE VERIFICATION")
print("-" * 80)
print(f"Expected Rows: {expected_rows}")
print(f"Current Rows: {df.shape[0]}")
print(f"Row Count Difference: {df.shape[0] - expected_rows}")

print(f"\nExpected Columns: {expected_columns}")
print(f"Current Columns: {df.shape[1]}")
print(f"Column Count Difference: {df.shape[1] - expected_columns}")

print("\nCOLUMN NAME CHECK")
print("-" * 80)
print(f"Duplicate Column Names Detected: {df.columns.duplicated().sum()}")

print("\nSTATUS")
print("-" * 80)

if df.shape[0] == expected_rows and df.shape[1] == expected_columns:
    print("Week 2 cleaned dataset baseline loaded successfully.")
    print("Dataset structure matches the locked Week 2 baseline.")
else:
    print("WARNING: Dataset structure does not match the expected Week 2 baseline.")

STEP 17.1A — FEATURE ENGINEERING DATASET LOADING & BASELINE SETUP

DATASET LOAD STATUS
--------------------------------------------------------------------------------
Dataset File: Logistic_Data_Analyst_Cleaned_Week2.csv
Current Dataset Rows: 180519
Current Dataset Columns: 55

BASELINE STRUCTURE VERIFICATION
--------------------------------------------------------------------------------
Expected Rows: 180519
Current Rows: 180519
Row Count Difference: 0

Expected Columns: 55
Current Columns: 55
Column Count Difference: 0

COLUMN NAME CHECK
--------------------------------------------------------------------------------
Duplicate Column Names Detected: 0

STATUS
--------------------------------------------------------------------------------
Week 2 cleaned dataset baseline loaded successfully.
Dataset structure matches the locked Week 2 baseline.


## STEP 17.1B — SOURCE DATA TYPE RESTORATION & VERIFICATION

The Week 2 cleaned dataset was exported and reloaded through CSV format for Feature Engineering.

CSV files do not permanently preserve pandas datetime data types. Therefore, source data types must be verified before creating date-derived and operational features.

This step will:

- Inspect the current data types of all columns
- Verify the required date columns
- Restore approved datetime columns where required
- Verify the Late delivery risk boolean field
- Confirm numerical source columns remain numerical
- Confirm dataset rows and columns remain unchanged

No feature engineering columns will be created in this step.
No rows or columns will be removed.

In [18]:
# STEP 17.1B — SOURCE DATA TYPE RESTORATION & VERIFICATION

expected_rows = 180519
expected_columns = 55

date_columns = [
    "order date (DateOrders)",
    "shipping date (DateOrders)"
]

required_numeric_columns = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Benefit per order",
    "Order Item Discount",
    "Order Item Discount Rate",
    "Order Item Product Price",
    "Order Item Profit Ratio",
    "Order Item Quantity",
    "Sales",
    "Order Item Total"
]

print("STEP 17.1B — SOURCE DATA TYPE RESTORATION & VERIFICATION")
print("=" * 80)

print("\nDATE COLUMN DATA TYPE RESTORATION")
print("-" * 80)

for column in date_columns:
    print(f"{column}: {df[column].dtype}")

print("\nRESTORING APPROVED DATETIME COLUMNS")
print("-" * 80)

df["order date (DateOrders)"] = pd.to_datetime(
    df["order date (DateOrders)"],
    errors="coerce"
)

df["shipping date (DateOrders)"] = pd.to_datetime(
    df["shipping date (DateOrders)"],
    errors="coerce"
)

date_type_verification = pd.DataFrame({
    "Date Column": date_columns,
    "Current Data Type": [
        df["order date (DateOrders)"].dtype,
        df["shipping date (DateOrders)"].dtype
    ],
    "Missing Values": [
        df["order date (DateOrders)"].isna().sum(),
        df["shipping date (DateOrders)"].isna().sum()
    ]
})

print(date_type_verification.to_string(index=False))

print("\nREQUIRED NUMERICAL SOURCE COLUMN VERIFICATION")
print("-" * 80)

numeric_verification = pd.DataFrame({
    "Column": required_numeric_columns,
    "Data Type": [df[column].dtype for column in required_numeric_columns],
    "Is Numeric": [
        pd.api.types.is_numeric_dtype(df[column])
        for column in required_numeric_columns
    ]
})

print(numeric_verification.to_string(index=False))

print("\nBOOLEAN FIELD VERIFICATION")
print("-" * 80)

print(f"Late delivery risk Data Type: {df['Late delivery risk'].dtype}")

print("\nDATASET STRUCTURAL INTEGRITY")
print("-" * 80)

integrity_summary = pd.DataFrame({
    "Metric": [
        "Current Dataset Rows",
        "Expected Dataset Rows",
        "Row Count Difference",
        "Current Dataset Columns",
        "Expected Dataset Columns",
        "Column Count Difference"
    ],
    "Value": [
        df.shape[0],
        expected_rows,
        df.shape[0] - expected_rows,
        df.shape[1],
        expected_columns,
        df.shape[1] - expected_columns
    ]
})

print(integrity_summary.to_string(index=False))

print("\nSTATUS")
print("-" * 80)
print("Source data type verification completed.")
print("Approved datetime columns were restored for Feature Engineering.")
print("Required numerical source columns were verified.")
print("No engineered features were created in this step.")
print("No rows were removed.")
print("No columns were removed.")

STEP 17.1B — SOURCE DATA TYPE RESTORATION & VERIFICATION

DATE COLUMN DATA TYPE RESTORATION
--------------------------------------------------------------------------------
order date (DateOrders): object
shipping date (DateOrders): object

RESTORING APPROVED DATETIME COLUMNS
--------------------------------------------------------------------------------
               Date Column Current Data Type  Missing Values
   order date (DateOrders)    datetime64[ns]               0
shipping date (DateOrders)    datetime64[ns]               0

REQUIRED NUMERICAL SOURCE COLUMN VERIFICATION
--------------------------------------------------------------------------------
                       Column Data Type  Is Numeric
     Days for shipping (real)     int64        True
Days for shipment (scheduled)     int64        True
            Benefit per order   float64        True
          Order Item Discount   float64        True
     Order Item Discount Rate   float64        True
     Order Item Pro

## STEP 17.1C — FEATURE ENGINEERING SOURCE READINESS & PLANNED FEATURE REGISTER

Before creating engineered features, the cleaned Week 2 dataset must be verified against the approved Feature Engineering requirements.

This step will:

- Verify all required source columns for planned feature creation
- Confirm source column availability
- Confirm that planned engineered columns do not already exist
- Register the approved feature engineering categories
- Preserve the Week 2 cleaned dataset baseline before modification

The planned feature engineering scope includes:

- Delivery and transit features
- Delay and performance indicators
- Date-derived features
- Commercial and operational indicators
- Logistics corridor and shipping lane features
- Cross-border indicators

No engineered columns will be created in this step.
No existing source columns will be modified.
No rows or columns will be removed.

In [19]:
# STEP 17.1C — FEATURE ENGINEERING SOURCE READINESS & PLANNED FEATURE REGISTER

baseline_rows = df.shape[0]
baseline_columns = df.shape[1]

required_source_columns = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "order date (DateOrders)",
    "shipping date (DateOrders)",
    "Benefit per order",
    "Market",
    "Order Region",
    "Customer State",
    "Customer Country",
    "Order Country"
]

planned_engineered_columns = [
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Performance_Category",
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Order_Day_of_Week",
    "Is_Weekend_Order",
    "Is_Commercial_Loss",
    "Delay_Severity_Level",
    "Logistics_Corridor_ID",
    "Shipping_Lane_ID",
    "Is_Cross_Border"
]

print("STEP 17.1C — FEATURE ENGINEERING SOURCE READINESS & PLANNED FEATURE REGISTER")
print("=" * 80)

print("\nREQUIRED SOURCE COLUMN VERIFICATION")
print("-" * 80)

source_verification = pd.DataFrame({
    "Required Source Column": required_source_columns,
    "Available": [
        "YES" if column in df.columns else "NO"
        for column in required_source_columns
    ]
})

print(source_verification.to_string(index=False))

available_source_columns = sum(
    column in df.columns
    for column in required_source_columns
)

print("\nFEATURE ENGINEERING SOURCE READINESS")
print("-" * 80)

readiness_summary = pd.DataFrame({
    "Metric": [
        "Required Source Columns",
        "Available Source Columns",
        "Missing Source Columns"
    ],
    "Value": [
        len(required_source_columns),
        available_source_columns,
        len(required_source_columns) - available_source_columns
    ]
})

print(readiness_summary.to_string(index=False))

print("\nEXISTING APPROVED ENGINEERED COLUMN CHECK")
print("-" * 80)

engineered_column_check = pd.DataFrame({
    "Planned Engineered Column": planned_engineered_columns,
    "Already Present": [
        "YES" if column in df.columns else "NO"
        for column in planned_engineered_columns
    ]
})

print(engineered_column_check.to_string(index=False))

existing_engineered_columns = sum(
    column in df.columns
    for column in planned_engineered_columns
)

print("\nPLANNED FEATURE ENGINEERING CATEGORIES")
print("-" * 80)

feature_categories = pd.DataFrame({
    "Feature Category": [
        "Delivery and Transit Features",
        "Delay and Performance Indicators",
        "Date-Derived Features",
        "Commercial and Operational Indicators",
        "Logistics Corridor Features",
        "Shipping Lane Features",
        "Cross-Border Indicators"
    ],
    "Status": [
        "APPROVED FOR ENGINEERING",
        "APPROVED FOR ENGINEERING",
        "APPROVED FOR ENGINEERING",
        "APPROVED FOR ENGINEERING",
        "APPROVED FOR ENGINEERING",
        "APPROVED FOR ENGINEERING",
        "APPROVED FOR ENGINEERING"
    ]
})

print(feature_categories.to_string(index=False))

print("\nDATASET BASELINE INTEGRITY")
print("-" * 80)

integrity_check = pd.DataFrame({
    "Metric": [
        "Baseline Dataset Rows",
        "Current Dataset Rows",
        "Row Count Difference",
        "Baseline Dataset Columns",
        "Current Dataset Columns",
        "Column Count Difference",
        "Duplicate Column Names"
    ],
    "Value": [
        baseline_rows,
        df.shape[0],
        df.shape[0] - baseline_rows,
        baseline_columns,
        df.shape[1],
        df.shape[1] - baseline_columns,
        df.columns.duplicated().sum()
    ]
})

print(integrity_check.to_string(index=False))

print("\nSTATUS")
print("-" * 80)
print("Feature engineering source readiness verification completed.")
print(f"Required source columns available: {available_source_columns}/{len(required_source_columns)}")
print(f"Planned engineered columns already present: {existing_engineered_columns}")
print("No engineered features were created in this step.")
print("No source columns were modified.")
print("No rows were removed.")
print("No columns were removed.")

STEP 17.1C — FEATURE ENGINEERING SOURCE READINESS & PLANNED FEATURE REGISTER

REQUIRED SOURCE COLUMN VERIFICATION
--------------------------------------------------------------------------------
       Required Source Column Available
     Days for shipping (real)       YES
Days for shipment (scheduled)       YES
      order date (DateOrders)       YES
   shipping date (DateOrders)       YES
            Benefit per order       YES
                       Market       YES
                 Order Region       YES
               Customer State       YES
             Customer Country       YES
                Order Country       YES

FEATURE ENGINEERING SOURCE READINESS
--------------------------------------------------------------------------------
                  Metric  Value
 Required Source Columns     10
Available Source Columns     10
  Missing Source Columns      0

EXISTING APPROVED ENGINEERED COLUMN CHECK
---------------------------------------------------------------------------

## STEP 17.2 — DELIVERY AND TRANSIT FEATURE ENGINEERING

This step creates delivery and transit-related analytical features using the approved shipping duration source columns.

The following engineered features will be created:

- Delivery_Time_Hours
- Promised_Time_Hours
- Delay_Hours

Feature logic:

- Delivery_Time_Hours = Days for shipping (real) × 24
- Promised_Time_Hours = Days for shipment (scheduled) × 24
- Delay_Hours = Delivery_Time_Hours − Promised_Time_Hours

These features convert shipping durations into a common hourly analytical scale and provide a direct measure of delivery deviation from the scheduled transit duration.

Original source columns will remain unchanged.

Mathematical validation and dataset integrity verification will be performed after feature creation.

In [20]:
# STEP 17.2 — DELIVERY AND TRANSIT FEATURE ENGINEERING

rows_before = df.shape[0]
columns_before = df.shape[1]

print("STEP 17.2 — DELIVERY AND TRANSIT FEATURE ENGINEERING")
print("=" * 80)

print("\nFEATURE CREATION")
print("-" * 80)

df["Delivery_Time_Hours"] = df["Days for shipping (real)"] * 24

df["Promised_Time_Hours"] = df["Days for shipment (scheduled)"] * 24

df["Delay_Hours"] = (
    df["Delivery_Time_Hours"]
    - df["Promised_Time_Hours"]
)

engineered_features = [
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours"
]

feature_creation_summary = pd.DataFrame({
    "Engineered Feature": engineered_features,
    "Created": [
        "YES" if column in df.columns else "NO"
        for column in engineered_features
    ],
    "Missing Values": [
        df[column].isna().sum()
        for column in engineered_features
    ],
    "Infinite Values": [
        np.isinf(df[column]).sum()
        for column in engineered_features
    ]
})

print(feature_creation_summary.to_string(index=False))

print("\nMATHEMATICAL VALIDATION")
print("-" * 80)

delivery_formula_check = (
    df["Delivery_Time_Hours"]
    == df["Days for shipping (real)"] * 24
).all()

promised_formula_check = (
    df["Promised_Time_Hours"]
    == df["Days for shipment (scheduled)"] * 24
).all()

delay_formula_check = (
    df["Delay_Hours"]
    == (
        df["Delivery_Time_Hours"]
        - df["Promised_Time_Hours"]
    )
).all()

mathematical_validation = pd.DataFrame({
    "Verification Check": [
        "Delivery_Time_Hours Formula Correct",
        "Promised_Time_Hours Formula Correct",
        "Delay_Hours Formula Correct",
        "Original Source Columns Preserved"
    ],
    "Result": [
        "PASS" if delivery_formula_check else "FAIL",
        "PASS" if promised_formula_check else "FAIL",
        "PASS" if delay_formula_check else "FAIL",
        "PASS" if (
            "Days for shipping (real)" in df.columns
            and "Days for shipment (scheduled)" in df.columns
        ) else "FAIL"
    ]
})

print(mathematical_validation.to_string(index=False))

print("\nDATASET STRUCTURAL INTEGRITY")
print("-" * 80)

structural_integrity = pd.DataFrame({
    "Metric": [
        "Dataset Rows Before",
        "Current Dataset Rows",
        "Row Count Difference",
        "Dataset Columns Before",
        "Current Dataset Columns",
        "New Columns Created",
        "Expected New Columns",
        "Column Creation Difference"
    ],
    "Value": [
        rows_before,
        df.shape[0],
        df.shape[0] - rows_before,
        columns_before,
        df.shape[1],
        df.shape[1] - columns_before,
        3,
        (df.shape[1] - columns_before) - 3
    ]
})

print(structural_integrity.to_string(index=False))

print("\nSTATUS")
print("-" * 80)
print("Delivery and transit feature engineering completed.")
print("Three new analytical features were created.")
print("Original source columns remain preserved.")
print("Mathematical feature relationships were validated.")
print("No rows were removed.")
print("No existing columns were removed.")

STEP 17.2 — DELIVERY AND TRANSIT FEATURE ENGINEERING

FEATURE CREATION
--------------------------------------------------------------------------------
 Engineered Feature Created  Missing Values  Infinite Values
Delivery_Time_Hours     YES               0                0
Promised_Time_Hours     YES               0                0
        Delay_Hours     YES               0                0

MATHEMATICAL VALIDATION
--------------------------------------------------------------------------------
                 Verification Check Result
Delivery_Time_Hours Formula Correct   PASS
Promised_Time_Hours Formula Correct   PASS
        Delay_Hours Formula Correct   PASS
  Original Source Columns Preserved   PASS

DATASET STRUCTURAL INTEGRITY
--------------------------------------------------------------------------------
                    Metric  Value
       Dataset Rows Before 180519
      Current Dataset Rows 180519
      Row Count Difference      0
    Dataset Columns Before     55
  

## STEP 17.3 — DELAY AND PERFORMANCE INDICATOR ENGINEERING

This step creates analytical indicators that classify delivery performance using the previously engineered Delay_Hours feature.

The following features will be created:

- Delay_Flag
- Performance_Category
- Delay_Severity_Level

Feature logic:

Delay_Flag:
- True when Delay_Hours is greater than 0
- False when Delay_Hours is less than or equal to 0

Performance_Category:
- Early when Delay_Hours is less than 0
- On Time when Delay_Hours equals 0
- Delayed when Delay_Hours is greater than 0

Delay_Severity_Level:
- On Time / Early when Delay_Hours is less than or equal to 0
- Low Delay when Delay_Hours is greater than 0 and less than or equal to 24
- Moderate Delay when Delay_Hours is greater than 24 and less than or equal to 48
- High Delay when Delay_Hours is greater than 48

The original delivery and transit source columns will remain unchanged.

Feature logic, category consistency, and dataset structural integrity will be validated after creation.

In [21]:
# STEP 17.3 — DELAY AND PERFORMANCE INDICATOR ENGINEERING

rows_before = df.shape[0]
columns_before = df.shape[1]

print("STEP 17.3 — DELAY AND PERFORMANCE INDICATOR ENGINEERING")
print("=" * 80)

print("\nDELAY AND PERFORMANCE FEATURE CREATION")
print("-" * 80)

df["Delay_Flag"] = df["Delay_Hours"] > 0

df["Performance_Category"] = np.select(
    [
        df["Delay_Hours"] < 0,
        df["Delay_Hours"] == 0,
        df["Delay_Hours"] > 0
    ],
    [
        "Early",
        "On Time",
        "Delayed"
    ],
    default="Unknown"
)

df["Delay_Severity_Level"] = np.select(
    [
        df["Delay_Hours"] <= 0,
        (df["Delay_Hours"] > 0) & (df["Delay_Hours"] <= 24),
        (df["Delay_Hours"] > 24) & (df["Delay_Hours"] <= 48),
        df["Delay_Hours"] > 48
    ],
    [
        "On Time / Early",
        "Low Delay",
        "Moderate Delay",
        "High Delay"
    ],
    default="Unknown"
)

engineered_features = [
    "Delay_Flag",
    "Performance_Category",
    "Delay_Severity_Level"
]

feature_summary = pd.DataFrame({
    "Engineered Feature": engineered_features,
    "Created": [
        "YES" if column in df.columns else "NO"
        for column in engineered_features
    ],
    "Missing Values": [
        df[column].isna().sum()
        for column in engineered_features
    ],
    "Unique Values": [
        df[column].nunique(dropna=False)
        for column in engineered_features
    ]
})

print(feature_summary.to_string(index=False))

print("\nPERFORMANCE CATEGORY DISTRIBUTION")
print("-" * 80)
print(
    df["Performance_Category"]
    .value_counts(dropna=False)
    .to_string()
)

print("\nDELAY SEVERITY DISTRIBUTION")
print("-" * 80)
print(
    df["Delay_Severity_Level"]
    .value_counts(dropna=False)
    .to_string()
)

print("\nLOGICAL FEATURE VALIDATION")
print("-" * 80)

delay_flag_validation = (
    df["Delay_Flag"]
    == (df["Delay_Hours"] > 0)
).all()

performance_validation = (
    (
        (df["Performance_Category"] == "Early")
        & (df["Delay_Hours"] < 0)
    )
    |
    (
        (df["Performance_Category"] == "On Time")
        & (df["Delay_Hours"] == 0)
    )
    |
    (
        (df["Performance_Category"] == "Delayed")
        & (df["Delay_Hours"] > 0)
    )
).all()

severity_validation = (
    (
        (df["Delay_Severity_Level"] == "On Time / Early")
        & (df["Delay_Hours"] <= 0)
    )
    |
    (
        (df["Delay_Severity_Level"] == "Low Delay")
        & (df["Delay_Hours"] > 0)
        & (df["Delay_Hours"] <= 24)
    )
    |
    (
        (df["Delay_Severity_Level"] == "Moderate Delay")
        & (df["Delay_Hours"] > 24)
        & (df["Delay_Hours"] <= 48)
    )
    |
    (
        (df["Delay_Severity_Level"] == "High Delay")
        & (df["Delay_Hours"] > 48)
    )
).all()

validation_summary = pd.DataFrame({
    "Verification Check": [
        "Delay_Flag Logic Correct",
        "Performance_Category Logic Correct",
        "Delay_Severity_Level Logic Correct",
        "No Unknown Performance Categories",
        "No Unknown Severity Categories"
    ],
    "Result": [
        "PASS" if delay_flag_validation else "FAIL",
        "PASS" if performance_validation else "FAIL",
        "PASS" if severity_validation else "FAIL",
        "PASS" if (df["Performance_Category"] == "Unknown").sum() == 0 else "FAIL",
        "PASS" if (df["Delay_Severity_Level"] == "Unknown").sum() == 0 else "FAIL"
    ]
})

print(validation_summary.to_string(index=False))

print("\nDATASET STRUCTURAL INTEGRITY")
print("-" * 80)

integrity_summary = pd.DataFrame({
    "Metric": [
        "Dataset Rows Before",
        "Current Dataset Rows",
        "Row Count Difference",
        "Dataset Columns Before",
        "Current Dataset Columns",
        "New Columns Created",
        "Expected New Columns",
        "Column Creation Difference"
    ],
    "Value": [
        rows_before,
        df.shape[0],
        df.shape[0] - rows_before,
        columns_before,
        df.shape[1],
        df.shape[1] - columns_before,
        3,
        (df.shape[1] - columns_before) - 3
    ]
})

print(integrity_summary.to_string(index=False))

print("\nSTATUS")
print("-" * 80)
print("Delay and performance indicator engineering completed.")
print("Three new analytical indicators were created.")
print("Feature logic was validated successfully.")
print("No rows were removed.")
print("No existing columns were removed.")

STEP 17.3 — DELAY AND PERFORMANCE INDICATOR ENGINEERING

DELAY AND PERFORMANCE FEATURE CREATION
--------------------------------------------------------------------------------
  Engineered Feature Created  Missing Values  Unique Values
          Delay_Flag     YES               0              2
Performance_Category     YES               0              3
Delay_Severity_Level     YES               0              4

PERFORMANCE CATEGORY DISTRIBUTION
--------------------------------------------------------------------------------
Performance_Category
Delayed    103400
Early       43366
On Time     33753

DELAY SEVERITY DISTRIBUTION
--------------------------------------------------------------------------------
Delay_Severity_Level
On Time / Early    77119
Low Delay          60647
Moderate Delay     28718
High Delay         14035

LOGICAL FEATURE VALIDATION
--------------------------------------------------------------------------------
                Verification Check Result
          

# STEP 17.4 — DATE-DERIVED FEATURE ENGINEERING

This step creates analytical date-derived features from the approved `order date (DateOrders)` column.

The purpose is to extract temporal information that can support logistics analysis, seasonal pattern analysis, monthly performance analysis, and weekday versus weekend operational comparisons.

The following features will be created:

- Order_Year
- Order_Month
- Order_Month_Name
- Order_Day_of_Week
- Is_Weekend_Order

The original date column will remain unchanged.

No rows will be removed.
No existing columns will be removed.
Dataset structure will be validated after feature creation.

In [22]:
import pandas as pd

print("STEP 17.4 — DATE-DERIVED FEATURE ENGINEERING")
print("=" * 80)

# Baseline before feature creation
rows_before = df.shape[0]
columns_before = df.shape[1]

print("\nDATE SOURCE COLUMN VERIFICATION")
print("-" * 80)

date_column = "order date (DateOrders)"

if date_column not in df.columns:
    raise ValueError(f"Required source column not found: {date_column}")

if not pd.api.types.is_datetime64_any_dtype(df[date_column]):
    raise TypeError(
        f"{date_column} must be datetime64 before date feature engineering. "
        f"Current data type: {df[date_column].dtype}"
    )

print(f"Source Column: {date_column}")
print(f"Data Type: {df[date_column].dtype}")
print(f"Missing Values: {df[date_column].isna().sum()}")

# Create date-derived features
df["Order_Year"] = df[date_column].dt.year
df["Order_Month"] = df[date_column].dt.month
df["Order_Month_Name"] = df[date_column].dt.month_name()
df["Order_Day_of_Week"] = df[date_column].dt.day_name()
df["Is_Weekend_Order"] = df[date_column].dt.dayofweek.isin([5, 6])

engineered_features = [
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Order_Day_of_Week",
    "Is_Weekend_Order"
]

print("\nDATE-DERIVED FEATURE CREATION")
print("-" * 80)

feature_creation_results = []

for feature in engineered_features:
    feature_creation_results.append({
        "Engineered Feature": feature,
        "Created": "YES" if feature in df.columns else "NO",
        "Missing Values": df[feature].isna().sum(),
        "Unique Values": df[feature].nunique(dropna=False)
    })

display(pd.DataFrame(feature_creation_results))

print("\nDATE FEATURE LOGICAL VALIDATION")
print("-" * 80)

validation_results = pd.DataFrame({
    "Verification Check": [
        "Order_Year Created",
        "Order_Month Created",
        "Order_Month_Name Created",
        "Order_Day_of_Week Created",
        "Is_Weekend_Order Created",
        "Original Date Column Preserved"
    ],
    "Result": [
        "PASS" if "Order_Year" in df.columns else "FAIL",
        "PASS" if "Order_Month" in df.columns else "FAIL",
        "PASS" if "Order_Month_Name" in df.columns else "FAIL",
        "PASS" if "Order_Day_of_Week" in df.columns else "FAIL",
        "PASS" if "Is_Weekend_Order" in df.columns else "FAIL",
        "PASS" if date_column in df.columns else "FAIL"
    ]
})

display(validation_results)

print("\nDATE FEATURE DISTRIBUTION")
print("-" * 80)

date_distribution = pd.DataFrame({
    "Metric": [
        "Order Year Range",
        "Order Month Range",
        "Weekend Orders",
        "Weekday Orders"
    ],
    "Value": [
        f"{df['Order_Year'].min()} to {df['Order_Year'].max()}",
        f"{df['Order_Month'].min()} to {df['Order_Month'].max()}",
        int(df["Is_Weekend_Order"].sum()),
        int((~df["Is_Weekend_Order"]).sum())
    ]
})

display(date_distribution)

print("\nDATASET STRUCTURAL INTEGRITY")
print("-" * 80)

rows_after = df.shape[0]
columns_after = df.shape[1]

integrity_summary = pd.DataFrame({
    "Metric": [
        "Dataset Rows Before",
        "Current Dataset Rows",
        "Row Count Difference",
        "Dataset Columns Before",
        "Current Dataset Columns",
        "New Columns Created",
        "Expected New Columns",
        "Column Creation Difference"
    ],
    "Value": [
        rows_before,
        rows_after,
        rows_after - rows_before,
        columns_before,
        columns_after,
        columns_after - columns_before,
        5,
        (columns_after - columns_before) - 5
    ]
})

display(integrity_summary)

print("\nSTATUS")
print("-" * 80)
print("Date-derived feature engineering completed.")
print("Five new analytical date features were created.")
print("Original date source column remains preserved.")
print("No rows were removed.")
print("No existing columns were removed.")

STEP 17.4 — DATE-DERIVED FEATURE ENGINEERING

DATE SOURCE COLUMN VERIFICATION
--------------------------------------------------------------------------------
Source Column: order date (DateOrders)
Data Type: datetime64[ns]
Missing Values: 0

DATE-DERIVED FEATURE CREATION
--------------------------------------------------------------------------------


,Engineered Feature,Created,Missing Values,Unique Values
0,Order_Year,YES,0,4
1,Order_Month,YES,0,12
2,Order_Month_Name,YES,0,12
3,Order_Day_of_Week,YES,0,7
4,Is_Weekend_Order,YES,0,2



DATE FEATURE LOGICAL VALIDATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Order_Year Created,PASS
1,Order_Month Created,PASS
2,Order_Month_Name Created,PASS
3,Order_Day_of_Week Created,PASS
4,Is_Weekend_Order Created,PASS
5,Original Date Column Preserved,PASS



DATE FEATURE DISTRIBUTION
--------------------------------------------------------------------------------


,Metric,Value
0,Order Year Range,2015 to 2018
1,Order Month Range,1 to 12
2,Weekend Orders,51847
3,Weekday Orders,128672



DATASET STRUCTURAL INTEGRITY
--------------------------------------------------------------------------------


,Metric,Value
0,Dataset Rows Before,180519
1,Current Dataset Rows,180519
2,Row Count Difference,0
3,Dataset Columns Before,61
4,Current Dataset Columns,66
5,New Columns Created,5
6,Expected New Columns,5
7,Column Creation Difference,0



STATUS
--------------------------------------------------------------------------------
Date-derived feature engineering completed.
Five new analytical date features were created.
Original date source column remains preserved.
No rows were removed.
No existing columns were removed.


# STEP 17.5 — COMMERCIAL AND OPERATIONAL INDICATOR ENGINEERING

This step creates a commercial performance indicator from the approved `Benefit per order` source column.

The purpose is to identify orders that generated a negative commercial benefit and distinguish them from non-loss-making orders.

The following feature will be created:

- Is_Commercial_Loss

Feature logic:

- True: Benefit per order is less than 0
- False: Benefit per order is greater than or equal to 0

The original `Benefit per order` column will remain unchanged.

No rows will be removed.
No existing columns will be removed.
Dataset structure will be validated after feature creation.

In [23]:
import pandas as pd

print("STEP 17.5 — COMMERCIAL AND OPERATIONAL INDICATOR ENGINEERING")
print("=" * 80)

# Baseline before feature creation
rows_before = df.shape[0]
columns_before = df.shape[1]

source_column = "Benefit per order"
engineered_feature = "Is_Commercial_Loss"

print("\nSOURCE COLUMN VERIFICATION")
print("-" * 80)

if source_column not in df.columns:
    raise ValueError(f"Required source column not found: {source_column}")

if not pd.api.types.is_numeric_dtype(df[source_column]):
    raise TypeError(
        f"{source_column} must be numeric. Current data type: {df[source_column].dtype}"
    )

print(f"Source Column: {source_column}")
print(f"Data Type: {df[source_column].dtype}")
print(f"Missing Values: {df[source_column].isna().sum()}")

# Create commercial loss indicator
df[engineered_feature] = df[source_column] < 0

print("\nCOMMERCIAL INDICATOR CREATION")
print("-" * 80)

feature_creation_summary = pd.DataFrame({
    "Engineered Feature": [engineered_feature],
    "Created": ["YES" if engineered_feature in df.columns else "NO"],
    "Missing Values": [df[engineered_feature].isna().sum()],
    "Unique Values": [df[engineered_feature].nunique(dropna=False)],
    "Data Type": [str(df[engineered_feature].dtype)]
})

display(feature_creation_summary)

print("\nCOMMERCIAL LOSS DISTRIBUTION")
print("-" * 80)

commercial_loss_distribution = (
    df[engineered_feature]
    .value_counts(dropna=False)
    .rename_axis(engineered_feature)
    .reset_index(name="Order Count")
)

display(commercial_loss_distribution)

print("\nLOGICAL FEATURE VALIDATION")
print("-" * 80)

loss_logic_correct = (
    (df.loc[df[source_column] < 0, engineered_feature] == True).all()
)

non_loss_logic_correct = (
    (df.loc[df[source_column] >= 0, engineered_feature] == False).all()
)

validation_results = pd.DataFrame({
    "Verification Check": [
        "Is_Commercial_Loss Created",
        "Negative Benefit Classified as Commercial Loss",
        "Non-Negative Benefit Classified as Non-Loss",
        "Original Source Column Preserved",
        "No Missing Values in Engineered Feature"
    ],
    "Result": [
        "PASS" if engineered_feature in df.columns else "FAIL",
        "PASS" if loss_logic_correct else "FAIL",
        "PASS" if non_loss_logic_correct else "FAIL",
        "PASS" if source_column in df.columns else "FAIL",
        "PASS" if df[engineered_feature].isna().sum() == 0 else "FAIL"
    ]
})

display(validation_results)

print("\nDATASET STRUCTURAL INTEGRITY")
print("-" * 80)

rows_after = df.shape[0]
columns_after = df.shape[1]

integrity_summary = pd.DataFrame({
    "Metric": [
        "Dataset Rows Before",
        "Current Dataset Rows",
        "Row Count Difference",
        "Dataset Columns Before",
        "Current Dataset Columns",
        "New Columns Created",
        "Expected New Columns",
        "Column Creation Difference"
    ],
    "Value": [
        rows_before,
        rows_after,
        rows_after - rows_before,
        columns_before,
        columns_after,
        columns_after - columns_before,
        1,
        (columns_after - columns_before) - 1
    ]
})

display(integrity_summary)

print("\nSTATUS")
print("-" * 80)
print("Commercial and operational indicator engineering completed.")
print("Is_Commercial_Loss was created successfully.")
print("Commercial loss logic was validated.")
print("Original source column remains preserved.")
print("No rows were removed.")
print("No existing columns were removed.")

STEP 17.5 — COMMERCIAL AND OPERATIONAL INDICATOR ENGINEERING

SOURCE COLUMN VERIFICATION
--------------------------------------------------------------------------------
Source Column: Benefit per order
Data Type: float64
Missing Values: 0

COMMERCIAL INDICATOR CREATION
--------------------------------------------------------------------------------


,Engineered Feature,Created,Missing Values,Unique Values,Data Type
0,Is_Commercial_Loss,YES,0,2,bool



COMMERCIAL LOSS DISTRIBUTION
--------------------------------------------------------------------------------


,Is_Commercial_Loss,Order Count
0,False,146735
1,True,33784



LOGICAL FEATURE VALIDATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Is_Commercial_Loss Created,PASS
1,Negative Benefit Classified as Commercial Loss,PASS
2,Non-Negative Benefit Classified as Non-Loss,PASS
3,Original Source Column Preserved,PASS
4,No Missing Values in Engineered Feature,PASS



DATASET STRUCTURAL INTEGRITY
--------------------------------------------------------------------------------


,Metric,Value
0,Dataset Rows Before,180519
1,Current Dataset Rows,180519
2,Row Count Difference,0
3,Dataset Columns Before,66
4,Current Dataset Columns,67
5,New Columns Created,1
6,Expected New Columns,1
7,Column Creation Difference,0



STATUS
--------------------------------------------------------------------------------
Commercial and operational indicator engineering completed.
Is_Commercial_Loss was created successfully.
Commercial loss logic was validated.
Original source column remains preserved.
No rows were removed.
No existing columns were removed.


# STEP 17.6 — LOGISTICS CORRIDOR FEATURE ENGINEERING

This step creates a logistics corridor identifier using the approved `Market` and `Order Region` source columns.

The purpose is to represent each market-region combination as a standardized logistics corridor for downstream logistics analysis, regional performance comparison, delivery analysis, and operational segmentation.

The following feature will be created:

- Logistics_Corridor_ID

Feature construction:

Market + " | " + Order Region

The original `Market` and `Order Region` source columns will remain unchanged.

No rows will be removed.
No existing columns will be removed.
Dataset structure and feature consistency will be validated after feature creation.

In [24]:
import pandas as pd

print("STEP 17.6 — LOGISTICS CORRIDOR FEATURE ENGINEERING")
print("=" * 80)

# Baseline before feature creation
rows_before = df.shape[0]
columns_before = df.shape[1]

source_columns = ["Market", "Order Region"]
engineered_feature = "Logistics_Corridor_ID"

print("\nSOURCE COLUMN VERIFICATION")
print("-" * 80)

source_verification = []

for column in source_columns:
    if column not in df.columns:
        raise ValueError(f"Required source column not found: {column}")

    source_verification.append({
        "Source Column": column,
        "Available": "YES",
        "Missing Values": df[column].isna().sum(),
        "Blank Values": df[column].astype("string").str.strip().eq("").sum(),
        "Unique Values": df[column].nunique(dropna=False)
    })

display(pd.DataFrame(source_verification))

# Create logistics corridor feature
df[engineered_feature] = (
    df["Market"].astype("string").str.strip()
    + " | "
    + df["Order Region"].astype("string").str.strip()
)

print("\nLOGISTICS CORRIDOR FEATURE CREATION")
print("-" * 80)

feature_creation_summary = pd.DataFrame({
    "Engineered Feature": [engineered_feature],
    "Created": ["YES" if engineered_feature in df.columns else "NO"],
    "Missing Values": [df[engineered_feature].isna().sum()],
    "Blank Values": [df[engineered_feature].astype("string").str.strip().eq("").sum()],
    "Unique Values": [df[engineered_feature].nunique(dropna=False)]
})

display(feature_creation_summary)

print("\nLOGISTICS CORRIDOR SAMPLE VALUES")
print("-" * 80)

corridor_samples = (
    df[engineered_feature]
    .value_counts()
    .head(10)
    .rename_axis("Logistics Corridor")
    .reset_index(name="Order Count")
)

display(corridor_samples)

print("\nLOGICAL FEATURE VALIDATION")
print("-" * 80)

feature_available = engineered_feature in df.columns

source_columns_preserved = all(
    column in df.columns for column in source_columns
)

missing_values = df[engineered_feature].isna().sum()

expected_feature = (
    df["Market"].astype("string").str.strip()
    + " | "
    + df["Order Region"].astype("string").str.strip()
)

formula_correct = df[engineered_feature].equals(expected_feature)

validation_results = pd.DataFrame({
    "Verification Check": [
        "Logistics_Corridor_ID Created",
        "Market Source Column Preserved",
        "Order Region Source Column Preserved",
        "Feature Construction Formula Correct",
        "No Missing Values in Engineered Feature"
    ],
    "Result": [
        "PASS" if feature_available else "FAIL",
        "PASS" if "Market" in df.columns else "FAIL",
        "PASS" if "Order Region" in df.columns else "FAIL",
        "PASS" if formula_correct else "FAIL",
        "PASS" if missing_values == 0 else "FAIL"
    ]
})

display(validation_results)

print("\nDATASET STRUCTURAL INTEGRITY")
print("-" * 80)

rows_after = df.shape[0]
columns_after = df.shape[1]

integrity_summary = pd.DataFrame({
    "Metric": [
        "Dataset Rows Before",
        "Current Dataset Rows",
        "Row Count Difference",
        "Dataset Columns Before",
        "Current Dataset Columns",
        "New Columns Created",
        "Expected New Columns",
        "Column Creation Difference"
    ],
    "Value": [
        rows_before,
        rows_after,
        rows_after - rows_before,
        columns_before,
        columns_after,
        columns_after - columns_before,
        1,
        (columns_after - columns_before) - 1
    ]
})

display(integrity_summary)

print("\nSTATUS")
print("-" * 80)
print("Logistics corridor feature engineering completed.")
print("Logistics_Corridor_ID was created successfully.")
print("Market and Order Region source columns remain preserved.")
print("Feature construction logic was validated.")
print("No rows were removed.")
print("No existing columns were removed.")

STEP 17.6 — LOGISTICS CORRIDOR FEATURE ENGINEERING

SOURCE COLUMN VERIFICATION
--------------------------------------------------------------------------------


,Source Column,Available,Missing Values,Blank Values,Unique Values
0,Market,YES,0,0,5
1,Order Region,YES,0,0,23



LOGISTICS CORRIDOR FEATURE CREATION
--------------------------------------------------------------------------------


,Engineered Feature,Created,Missing Values,Blank Values,Unique Values
0,Logistics_Corridor_ID,YES,0,0,23



LOGISTICS CORRIDOR SAMPLE VALUES
--------------------------------------------------------------------------------


,Logistics Corridor,Order Count
0,LATAM | Central America,28341
1,Europe | Western Europe,27109
2,LATAM | South America,14935
3,Pacific Asia | Oceania,10148
4,Europe | Northern Europe,9792
5,Pacific Asia | South-eastern Asia,9539
6,Europe | Southern Europe,9431
7,LATAM | Caribbean,8318
8,USCA | West of USA,7993
9,Pacific Asia | Southern Asia,7731



LOGICAL FEATURE VALIDATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Logistics_Corridor_ID Created,PASS
1,Market Source Column Preserved,PASS
2,Order Region Source Column Preserved,PASS
3,Feature Construction Formula Correct,PASS
4,No Missing Values in Engineered Feature,PASS



DATASET STRUCTURAL INTEGRITY
--------------------------------------------------------------------------------


,Metric,Value
0,Dataset Rows Before,180519
1,Current Dataset Rows,180519
2,Row Count Difference,0
3,Dataset Columns Before,67
4,Current Dataset Columns,68
5,New Columns Created,1
6,Expected New Columns,1
7,Column Creation Difference,0



STATUS
--------------------------------------------------------------------------------
Logistics corridor feature engineering completed.
Logistics_Corridor_ID was created successfully.
Market and Order Region source columns remain preserved.
Feature construction logic was validated.
No rows were removed.
No existing columns were removed.


# STEP 17.7 — SHIPPING LANE FEATURE ENGINEERING

This step creates a shipping lane identifier using the approved `Order Country` and `Order Region` source columns.

The purpose is to represent country-region shipment relationships as standardized shipping lanes for downstream logistics analysis, delivery performance comparison, geographic segmentation, and operational analysis.

The following feature will be created:

- Shipping_Lane_ID

Feature construction:

Order Country + " | " + Order Region

The original `Order Country` and `Order Region` source columns will remain unchanged.

No rows will be removed.
No existing columns will be removed.
Dataset structure and feature consistency will be validated after feature creation.

In [25]:
import pandas as pd

print("STEP 17.7 — SHIPPING LANE FEATURE ENGINEERING")
print("=" * 80)

# Baseline before feature creation
rows_before = df.shape[0]
columns_before = df.shape[1]

source_columns = ["Order Country", "Order Region"]
engineered_feature = "Shipping_Lane_ID"

print("\nSOURCE COLUMN VERIFICATION")
print("-" * 80)

source_verification = []

for column in source_columns:
    if column not in df.columns:
        raise ValueError(f"Required source column not found: {column}")

    source_verification.append({
        "Source Column": column,
        "Available": "YES",
        "Missing Values": df[column].isna().sum(),
        "Blank Values": df[column].astype("string").str.strip().eq("").sum(),
        "Unique Values": df[column].nunique(dropna=False)
    })

display(pd.DataFrame(source_verification))

# Create shipping lane feature
df[engineered_feature] = (
    df["Order Country"].astype("string").str.strip()
    + " | "
    + df["Order Region"].astype("string").str.strip()
)

print("\nSHIPPING LANE FEATURE CREATION")
print("-" * 80)

feature_creation_summary = pd.DataFrame({
    "Engineered Feature": [engineered_feature],
    "Created": ["YES" if engineered_feature in df.columns else "NO"],
    "Missing Values": [df[engineered_feature].isna().sum()],
    "Blank Values": [df[engineered_feature].astype("string").str.strip().eq("").sum()],
    "Unique Values": [df[engineered_feature].nunique(dropna=False)]
})

display(feature_creation_summary)

print("\nSHIPPING LANE SAMPLE VALUES")
print("-" * 80)

shipping_lane_samples = (
    df[engineered_feature]
    .value_counts()
    .head(10)
    .rename_axis("Shipping Lane")
    .reset_index(name="Order Count")
)

display(shipping_lane_samples)

print("\nLOGICAL FEATURE VALIDATION")
print("-" * 80)

expected_feature = (
    df["Order Country"].astype("string").str.strip()
    + " | "
    + df["Order Region"].astype("string").str.strip()
)

formula_correct = df[engineered_feature].equals(expected_feature)

validation_results = pd.DataFrame({
    "Verification Check": [
        "Shipping_Lane_ID Created",
        "Order Country Source Column Preserved",
        "Order Region Source Column Preserved",
        "Feature Construction Formula Correct",
        "No Missing Values in Engineered Feature"
    ],
    "Result": [
        "PASS" if engineered_feature in df.columns else "FAIL",
        "PASS" if "Order Country" in df.columns else "FAIL",
        "PASS" if "Order Region" in df.columns else "FAIL",
        "PASS" if formula_correct else "FAIL",
        "PASS" if df[engineered_feature].isna().sum() == 0 else "FAIL"
    ]
})

display(validation_results)

print("\nDATASET STRUCTURAL INTEGRITY")
print("-" * 80)

rows_after = df.shape[0]
columns_after = df.shape[1]

integrity_summary = pd.DataFrame({
    "Metric": [
        "Dataset Rows Before",
        "Current Dataset Rows",
        "Row Count Difference",
        "Dataset Columns Before",
        "Current Dataset Columns",
        "New Columns Created",
        "Expected New Columns",
        "Column Creation Difference"
    ],
    "Value": [
        rows_before,
        rows_after,
        rows_after - rows_before,
        columns_before,
        columns_after,
        columns_after - columns_before,
        1,
        (columns_after - columns_before) - 1
    ]
})

display(integrity_summary)

print("\nSTATUS")
print("-" * 80)
print("Shipping lane feature engineering completed.")
print("Shipping_Lane_ID was created successfully.")
print("Order Country and Order Region source columns remain preserved.")
print("Feature construction logic was validated.")
print("No rows were removed.")
print("No existing columns were removed.")

STEP 17.7 — SHIPPING LANE FEATURE ENGINEERING

SOURCE COLUMN VERIFICATION
--------------------------------------------------------------------------------


,Source Column,Available,Missing Values,Blank Values,Unique Values
0,Order Country,YES,0,0,164
1,Order Region,YES,0,0,23



SHIPPING LANE FEATURE CREATION
--------------------------------------------------------------------------------


,Engineered Feature,Created,Missing Values,Blank Values,Unique Values
0,Shipping_Lane_ID,YES,0,0,167



SHIPPING LANE SAMPLE VALUES
--------------------------------------------------------------------------------


,Shipping Lane,Order Count
0,France | Western Europe,13222
1,Mexico | Central America,13172
2,Germany | Western Europe,9564
3,Australia | Oceania,8497
4,USA | West of USA,7993
5,Brazil | South America,7987
6,United Kingdom | Northern Europe,7302
7,USA | East of USA,6915
8,USA | US Center,5887
9,China | Eastern Asia,5758



LOGICAL FEATURE VALIDATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Shipping_Lane_ID Created,PASS
1,Order Country Source Column Preserved,PASS
2,Order Region Source Column Preserved,PASS
3,Feature Construction Formula Correct,PASS
4,No Missing Values in Engineered Feature,PASS



DATASET STRUCTURAL INTEGRITY
--------------------------------------------------------------------------------


,Metric,Value
0,Dataset Rows Before,180519
1,Current Dataset Rows,180519
2,Row Count Difference,0
3,Dataset Columns Before,68
4,Current Dataset Columns,69
5,New Columns Created,1
6,Expected New Columns,1
7,Column Creation Difference,0



STATUS
--------------------------------------------------------------------------------
Shipping lane feature engineering completed.
Shipping_Lane_ID was created successfully.
Order Country and Order Region source columns remain preserved.
Feature construction logic was validated.
No rows were removed.
No existing columns were removed.


# STEP 17.8 — CROSS-BORDER INDICATOR FEATURE ENGINEERING

This step creates the approved cross-border logistics indicator using the Customer Country and Order Country source columns.

The feature identifies whether an order crosses a national border between the customer's country and the order destination country.

Source columns remain preserved.

No rows will be removed.
No existing columns will be removed.

In [26]:
# STEP 17.8 — CROSS-BORDER INDICATOR FEATURE ENGINEERING

import pandas as pd

print("STEP 17.8 — CROSS-BORDER INDICATOR FEATURE ENGINEERING")
print("=" * 80)

rows_before = df.shape[0]
columns_before = df.shape[1]

customer_country_col = "Customer Country"
order_country_col = "Order Country"

print("\nSOURCE COLUMN VERIFICATION")
print("-" * 80)

source_verification = pd.DataFrame({
    "Source Column": [
        customer_country_col,
        order_country_col
    ],
    "Available": [
        "YES" if customer_country_col in df.columns else "NO",
        "YES" if order_country_col in df.columns else "NO"
    ],
    "Missing Values": [
        df[customer_country_col].isna().sum() if customer_country_col in df.columns else "N/A",
        df[order_country_col].isna().sum() if order_country_col in df.columns else "N/A"
    ],
    "Blank Values": [
        df[customer_country_col].astype(str).str.strip().eq("").sum()
        if customer_country_col in df.columns else "N/A",
        df[order_country_col].astype(str).str.strip().eq("").sum()
        if order_country_col in df.columns else "N/A"
    ],
    "Unique Values": [
        df[customer_country_col].nunique() if customer_country_col in df.columns else "N/A",
        df[order_country_col].nunique() if order_country_col in df.columns else "N/A"
    ]
})

display(source_verification)

if customer_country_col not in df.columns or order_country_col not in df.columns:
    raise ValueError("Required source columns for Is_Cross_Border are missing.")

df["Is_Cross_Border"] = (
    df[customer_country_col].astype(str).str.strip()
    !=
    df[order_country_col].astype(str).str.strip()
)

print("\nCROSS-BORDER INDICATOR CREATION")
print("-" * 80)

feature_creation = pd.DataFrame({
    "Engineered Feature": ["Is_Cross_Border"],
    "Created": ["YES"],
    "Missing Values": [df["Is_Cross_Border"].isna().sum()],
    "Unique Values": [df["Is_Cross_Border"].nunique()],
    "Data Type": [str(df["Is_Cross_Border"].dtype)]
})

display(feature_creation)

print("\nCROSS-BORDER DISTRIBUTION")
print("-" * 80)

cross_border_distribution = (
    df["Is_Cross_Border"]
    .value_counts()
    .rename_axis("Is_Cross_Border")
    .reset_index(name="Order Count")
)

display(cross_border_distribution)

print("\nLOGICAL FEATURE VALIDATION")
print("-" * 80)

same_country_validation = (
    df.loc[
        df[customer_country_col].astype(str).str.strip()
        ==
        df[order_country_col].astype(str).str.strip(),
        "Is_Cross_Border"
    ]
    .eq(False)
    .all()
)

different_country_validation = (
    df.loc[
        df[customer_country_col].astype(str).str.strip()
        !=
        df[order_country_col].astype(str).str.strip(),
        "Is_Cross_Border"
    ]
    .eq(True)
    .all()
)

validation_results = pd.DataFrame({
    "Verification Check": [
        "Is_Cross_Border Created",
        "Same Country Classified as Non-Cross-Border",
        "Different Country Classified as Cross-Border",
        "Customer Country Source Column Preserved",
        "Order Country Source Column Preserved",
        "No Missing Values in Engineered Feature"
    ],
    "Result": [
        "PASS" if "Is_Cross_Border" in df.columns else "FAIL",
        "PASS" if same_country_validation else "FAIL",
        "PASS" if different_country_validation else "FAIL",
        "PASS" if customer_country_col in df.columns else "FAIL",
        "PASS" if order_country_col in df.columns else "FAIL",
        "PASS" if df["Is_Cross_Border"].isna().sum() == 0 else "FAIL"
    ]
})

display(validation_results)

print("\nDATASET STRUCTURAL INTEGRITY")
print("-" * 80)

rows_after = df.shape[0]
columns_after = df.shape[1]

structural_integrity = pd.DataFrame({
    "Metric": [
        "Dataset Rows Before",
        "Current Dataset Rows",
        "Row Count Difference",
        "Dataset Columns Before",
        "Current Dataset Columns",
        "New Columns Created",
        "Expected New Columns",
        "Column Creation Difference"
    ],
    "Value": [
        rows_before,
        rows_after,
        rows_after - rows_before,
        columns_before,
        columns_after,
        columns_after - columns_before,
        1,
        (columns_after - columns_before) - 1
    ]
})

display(structural_integrity)

print("\nSTATUS")
print("-" * 80)
print("Cross-border indicator feature engineering completed.")
print("Is_Cross_Border was created successfully.")
print("Customer Country and Order Country source columns remain preserved.")
print("Cross-border classification logic was validated.")
print("No rows were removed.")
print("No existing columns were removed.")

STEP 17.8 — CROSS-BORDER INDICATOR FEATURE ENGINEERING

SOURCE COLUMN VERIFICATION
--------------------------------------------------------------------------------


,Source Column,Available,Missing Values,Blank Values,Unique Values
0,Customer Country,YES,0,0,2
1,Order Country,YES,0,0,164



CROSS-BORDER INDICATOR CREATION
--------------------------------------------------------------------------------


,Engineered Feature,Created,Missing Values,Unique Values,Data Type
0,Is_Cross_Border,YES,0,2,bool



CROSS-BORDER DISTRIBUTION
--------------------------------------------------------------------------------


,Is_Cross_Border,Order Count
0,True,165077
1,False,15442



LOGICAL FEATURE VALIDATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Is_Cross_Border Created,PASS
1,Same Country Classified as Non-Cross-Border,PASS
2,Different Country Classified as Cross-Border,PASS
3,Customer Country Source Column Preserved,PASS
4,Order Country Source Column Preserved,PASS
5,No Missing Values in Engineered Feature,PASS



DATASET STRUCTURAL INTEGRITY
--------------------------------------------------------------------------------


,Metric,Value
0,Dataset Rows Before,180519
1,Current Dataset Rows,180519
2,Row Count Difference,0
3,Dataset Columns Before,69
4,Current Dataset Columns,70
5,New Columns Created,1
6,Expected New Columns,1
7,Column Creation Difference,0



STATUS
--------------------------------------------------------------------------------
Cross-border indicator feature engineering completed.
Is_Cross_Border was created successfully.
Customer Country and Order Country source columns remain preserved.
Cross-border classification logic was validated.
No rows were removed.
No existing columns were removed.


# STEP 17.9 — FINAL FEATURE ENGINEERING CONSOLIDATED VERIFICATION & LOCK

This final step consolidates and verifies all approved Feature Engineering activities completed during STEP 17.

The verification confirms:

- All 15 approved engineered features are available.
- Delivery and transit feature integrity is preserved.
- Delay and performance indicators are available.
- Date-derived features are available.
- Commercial loss indicator is available.
- Logistics corridor and shipping lane features are available.
- Cross-border indicator is available.
- Original cleaned dataset structure remains preserved.
- Dataset row count remains unchanged.
- No duplicate column names exist.
- No engineered columns are missing.

No new features will be created in this step.
No existing data values will be modified.
No rows will be removed.
No columns will be removed.

In [27]:
# STEP 17.9 — FINAL FEATURE ENGINEERING CONSOLIDATED VERIFICATION & LOCK

import pandas as pd
import numpy as np

print("STEP 17.9 — FINAL FEATURE ENGINEERING CONSOLIDATED VERIFICATION & LOCK")
print("=" * 80)

expected_rows = 180519
expected_cleaned_columns = 55
expected_engineered_columns = 15
expected_total_columns = 70

approved_engineered_features = [
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Performance_Category",
    "Delay_Severity_Level",
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Order_Day_of_Week",
    "Is_Weekend_Order",
    "Is_Commercial_Loss",
    "Logistics_Corridor_ID",
    "Shipping_Lane_ID",
    "Is_Cross_Border"
]

print("\nFINAL FEATURE ENGINEERING REGISTER")
print("-" * 80)

feature_register = pd.DataFrame({
    "Engineered Feature": approved_engineered_features,
    "Available": [
        "YES" if column in df.columns else "NO"
        for column in approved_engineered_features
    ],
    "Missing Values": [
        df[column].isna().sum() if column in df.columns else "N/A"
        for column in approved_engineered_features
    ],
    "Unique Values": [
        df[column].nunique() if column in df.columns else "N/A"
        for column in approved_engineered_features
    ],
    "Infinite Values": [
        np.isinf(df[column]).sum()
        if column in df.columns and pd.api.types.is_numeric_dtype(df[column])
        else 0
        for column in approved_engineered_features
    ]
})

display(feature_register)

print("\nFEATURE CATEGORY CONSOLIDATED VERIFICATION")
print("-" * 80)

feature_categories = pd.DataFrame({
    "Feature Engineering Category": [
        "Delivery and Transit Features",
        "Delay and Performance Indicators",
        "Date-Derived Features",
        "Commercial and Operational Indicators",
        "Logistics Corridor Features",
        "Shipping Lane Features",
        "Cross-Border Indicators"
    ],
    "Expected Features": [
        3,
        3,
        5,
        1,
        1,
        1,
        1
    ],
    "Available Features": [
        sum(column in df.columns for column in [
            "Delivery_Time_Hours",
            "Promised_Time_Hours",
            "Delay_Hours"
        ]),
        sum(column in df.columns for column in [
            "Delay_Flag",
            "Performance_Category",
            "Delay_Severity_Level"
        ]),
        sum(column in df.columns for column in [
            "Order_Year",
            "Order_Month",
            "Order_Month_Name",
            "Order_Day_of_Week",
            "Is_Weekend_Order"
        ]),
        sum(column in df.columns for column in [
            "Is_Commercial_Loss"
        ]),
        sum(column in df.columns for column in [
            "Logistics_Corridor_ID"
        ]),
        sum(column in df.columns for column in [
            "Shipping_Lane_ID"
        ]),
        sum(column in df.columns for column in [
            "Is_Cross_Border"
        ])
    ]
})

feature_categories["Status"] = np.where(
    feature_categories["Expected Features"] == feature_categories["Available Features"],
    "VERIFIED",
    "REVIEW REQUIRED"
)

display(feature_categories)

print("\nENGINEERED FEATURE DATA QUALITY VERIFICATION")
print("-" * 80)

available_engineered_features = [
    column for column in approved_engineered_features
    if column in df.columns
]

total_missing_engineered = df[available_engineered_features].isna().sum().sum()

numerical_engineered_features = [
    column for column in available_engineered_features
    if pd.api.types.is_numeric_dtype(df[column])
]

total_infinite_engineered = sum(
    np.isinf(df[column]).sum()
    for column in numerical_engineered_features
)

data_quality_verification = pd.DataFrame({
    "Verification Check": [
        "Approved Engineered Features Expected",
        "Approved Engineered Features Available",
        "Missing Engineered Features",
        "Total Missing Values Across Engineered Features",
        "Infinite Values Across Numerical Engineered Features"
    ],
    "Result": [
        expected_engineered_columns,
        len(available_engineered_features),
        expected_engineered_columns - len(available_engineered_features),
        total_missing_engineered,
        total_infinite_engineered
    ]
})

display(data_quality_verification)

print("\nDATASET STRUCTURAL INTEGRITY")
print("-" * 80)

current_rows = df.shape[0]
current_columns = df.shape[1]

duplicate_column_count = df.columns.duplicated().sum()

original_columns_detected = current_columns - len(available_engineered_features)

structural_integrity = pd.DataFrame({
    "Verification Check": [
        "Expected Dataset Rows",
        "Current Dataset Rows",
        "Row Count Difference",
        "Expected Cleaned Dataset Columns",
        "Original Cleaned Dataset Columns Detected",
        "Expected Engineered Features",
        "Engineered Features Detected",
        "Expected Total Dataset Columns",
        "Current Dataset Columns",
        "Column Count Difference",
        "Duplicate Column Names Detected"
    ],
    "Result": [
        expected_rows,
        current_rows,
        current_rows - expected_rows,
        expected_cleaned_columns,
        original_columns_detected,
        expected_engineered_columns,
        len(available_engineered_features),
        expected_total_columns,
        current_columns,
        current_columns - expected_total_columns,
        duplicate_column_count
    ]
})

display(structural_integrity)

print("\nFINAL CRITICAL FEATURE ENGINEERING VERIFICATION")
print("-" * 80)

all_features_available = (
    len(available_engineered_features) == expected_engineered_columns
)

row_structure_preserved = current_rows == expected_rows
column_structure_preserved = current_columns == expected_total_columns
original_structure_preserved = original_columns_detected == expected_cleaned_columns
no_duplicate_columns = duplicate_column_count == 0
no_infinite_engineered = total_infinite_engineered == 0

critical_verification = pd.DataFrame({
    "Verification Check": [
        "All 15 Approved Engineered Features Available",
        "Delivery and Transit Features Complete",
        "Delay and Performance Features Complete",
        "Date-Derived Features Complete",
        "Commercial Loss Feature Complete",
        "Logistics Corridor Feature Complete",
        "Shipping Lane Feature Complete",
        "Cross-Border Feature Complete",
        "Dataset Row Structure Preserved",
        "Original Cleaned Dataset Structure Preserved",
        "Final Dataset Column Structure Preserved",
        "Duplicate Column Names Detected",
        "No Infinite Values in Numerical Engineered Features"
    ],
    "Result": [
        "YES" if all_features_available else "NO",
        "YES" if feature_categories.iloc[0]["Status"] == "VERIFIED" else "NO",
        "YES" if feature_categories.iloc[1]["Status"] == "VERIFIED" else "NO",
        "YES" if feature_categories.iloc[2]["Status"] == "VERIFIED" else "NO",
        "YES" if feature_categories.iloc[3]["Status"] == "VERIFIED" else "NO",
        "YES" if feature_categories.iloc[4]["Status"] == "VERIFIED" else "NO",
        "YES" if feature_categories.iloc[5]["Status"] == "VERIFIED" else "NO",
        "YES" if feature_categories.iloc[6]["Status"] == "VERIFIED" else "NO",
        "YES" if row_structure_preserved else "NO",
        "YES" if original_structure_preserved else "NO",
        "YES" if column_structure_preserved else "NO",
        duplicate_column_count,
        "YES" if no_infinite_engineered else "NO"
    ]
})

display(critical_verification)

print("\nFINAL FEATURE ENGINEERING READINESS STATUS")
print("-" * 80)

final_readiness = pd.DataFrame({
    "Verification Area": [
        "Delivery and Transit Engineering",
        "Delay and Performance Engineering",
        "Date-Derived Engineering",
        "Commercial Indicator Engineering",
        "Logistics Corridor Engineering",
        "Shipping Lane Engineering",
        "Cross-Border Engineering",
        "Engineered Feature Availability",
        "Engineered Feature Data Quality",
        "Dataset Structural Integrity",
        "Original Cleaned Data Preservation",
        "Overall STEP 17 Readiness"
    ],
    "Status": [
        "VERIFIED" if feature_categories.iloc[0]["Status"] == "VERIFIED" else "REVIEW REQUIRED",
        "VERIFIED" if feature_categories.iloc[1]["Status"] == "VERIFIED" else "REVIEW REQUIRED",
        "VERIFIED" if feature_categories.iloc[2]["Status"] == "VERIFIED" else "REVIEW REQUIRED",
        "VERIFIED" if feature_categories.iloc[3]["Status"] == "VERIFIED" else "REVIEW REQUIRED",
        "VERIFIED" if feature_categories.iloc[4]["Status"] == "VERIFIED" else "REVIEW REQUIRED",
        "VERIFIED" if feature_categories.iloc[5]["Status"] == "VERIFIED" else "REVIEW REQUIRED",
        "VERIFIED" if feature_categories.iloc[6]["Status"] == "VERIFIED" else "REVIEW REQUIRED",
        "VERIFIED" if all_features_available else "REVIEW REQUIRED",
        "VERIFIED" if total_missing_engineered == 0 and no_infinite_engineered else "REVIEW REQUIRED",
        "VERIFIED" if row_structure_preserved and column_structure_preserved else "REVIEW REQUIRED",
        "VERIFIED" if original_structure_preserved else "REVIEW REQUIRED",
        "READY FOR FINAL LOCK" if (
            all_features_available
            and row_structure_preserved
            and column_structure_preserved
            and original_structure_preserved
            and no_duplicate_columns
            and no_infinite_engineered
        ) else "REVIEW REQUIRED"
    ]
})

display(final_readiness)

print("\nFINAL LOCK STATUS")
print("-" * 80)

if (
    all_features_available
    and row_structure_preserved
    and column_structure_preserved
    and original_structure_preserved
    and no_duplicate_columns
    and no_infinite_engineered
):
    print("SUCCESS: STEP 17 — FEATURE ENGINEERING IS OFFICIALLY LOCKED.")
    print()
    print("All 15 approved engineered features were successfully created and verified.")
    print("Delivery and transit analytical features were verified.")
    print("Delay and performance indicators were verified.")
    print("Date-derived analytical features were verified.")
    print("Commercial loss indicator was verified.")
    print("Logistics corridor and shipping lane features were verified.")
    print("Cross-border indicator was verified.")
    print()
    print(f"Dataset structure is locked at {current_rows} rows and {current_columns} columns.")
    print(f"Original cleaned dataset columns preserved: {original_columns_detected}.")
    print(f"Engineered features preserved: {len(available_engineered_features)}.")
    print("No duplicate column names were detected.")
    print("No rows were removed during Feature Engineering.")
    print("No existing cleaned dataset columns were removed.")
    print()
    print("WEEK 2 FEATURE ENGINEERING: COMPLETE AND LOCKED.")
else:
    print("WARNING: STEP 17 REQUIRES REVIEW BEFORE FINAL LOCK.")

STEP 17.9 — FINAL FEATURE ENGINEERING CONSOLIDATED VERIFICATION & LOCK

FINAL FEATURE ENGINEERING REGISTER
--------------------------------------------------------------------------------


,Engineered Feature,Available,Missing Values,Unique Values,Infinite Values
0,Delivery_Time_Hours,YES,0,7,0
1,Promised_Time_Hours,YES,0,4,0
2,Delay_Hours,YES,0,7,0
3,Delay_Flag,YES,0,2,0
4,Performance_Category,YES,0,3,0
5,Delay_Severity_Level,YES,0,4,0
6,Order_Year,YES,0,4,0
7,Order_Month,YES,0,12,0
8,Order_Month_Name,YES,0,12,0
9,Order_Day_of_Week,YES,0,7,0



FEATURE CATEGORY CONSOLIDATED VERIFICATION
--------------------------------------------------------------------------------


,Feature Engineering Category,Expected Features,Available Features,Status
0,Delivery and Transit Features,3,3,VERIFIED
1,Delay and Performance Indicators,3,3,VERIFIED
2,Date-Derived Features,5,5,VERIFIED
3,Commercial and Operational Indicators,1,1,VERIFIED
4,Logistics Corridor Features,1,1,VERIFIED
5,Shipping Lane Features,1,1,VERIFIED
6,Cross-Border Indicators,1,1,VERIFIED



ENGINEERED FEATURE DATA QUALITY VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Approved Engineered Features Expected,15
1,Approved Engineered Features Available,15
2,Missing Engineered Features,0
3,Total Missing Values Across Engineered Features,0
4,Infinite Values Across Numerical Engineered Fe...,0



DATASET STRUCTURAL INTEGRITY
--------------------------------------------------------------------------------


,Verification Check,Result
0,Expected Dataset Rows,180519
1,Current Dataset Rows,180519
2,Row Count Difference,0
3,Expected Cleaned Dataset Columns,55
4,Original Cleaned Dataset Columns Detected,55
5,Expected Engineered Features,15
6,Engineered Features Detected,15
7,Expected Total Dataset Columns,70
8,Current Dataset Columns,70
9,Column Count Difference,0



FINAL CRITICAL FEATURE ENGINEERING VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,All 15 Approved Engineered Features Available,YES
1,Delivery and Transit Features Complete,YES
2,Delay and Performance Features Complete,YES
3,Date-Derived Features Complete,YES
4,Commercial Loss Feature Complete,YES
5,Logistics Corridor Feature Complete,YES
6,Shipping Lane Feature Complete,YES
7,Cross-Border Feature Complete,YES
8,Dataset Row Structure Preserved,YES
9,Original Cleaned Dataset Structure Preserved,YES



FINAL FEATURE ENGINEERING READINESS STATUS
--------------------------------------------------------------------------------


,Verification Area,Status
0,Delivery and Transit Engineering,VERIFIED
1,Delay and Performance Engineering,VERIFIED
2,Date-Derived Engineering,VERIFIED
3,Commercial Indicator Engineering,VERIFIED
4,Logistics Corridor Engineering,VERIFIED
5,Shipping Lane Engineering,VERIFIED
6,Cross-Border Engineering,VERIFIED
7,Engineered Feature Availability,VERIFIED
8,Engineered Feature Data Quality,VERIFIED
9,Dataset Structural Integrity,VERIFIED



FINAL LOCK STATUS
--------------------------------------------------------------------------------
SUCCESS: STEP 17 — FEATURE ENGINEERING IS OFFICIALLY LOCKED.

All 15 approved engineered features were successfully created and verified.
Delivery and transit analytical features were verified.
Delay and performance indicators were verified.
Date-derived analytical features were verified.
Commercial loss indicator was verified.
Logistics corridor and shipping lane features were verified.
Cross-border indicator was verified.

Dataset structure is locked at 180519 rows and 70 columns.
Original cleaned dataset columns preserved: 55.
Engineered features preserved: 15.
No duplicate column names were detected.
No rows were removed during Feature Engineering.
No existing cleaned dataset columns were removed.

WEEK 2 FEATURE ENGINEERING: COMPLETE AND LOCKED.


In [31]:
import pandas as pd

# Expected locked dataset structure
expected_rows = 180519
expected_columns = 70

approved_engineered_features = [
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Performance_Category",
    "Delay_Severity_Level",
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Order_Day_of_Week",
    "Is_Weekend_Order",
    "Is_Commercial_Loss",
    "Logistics_Corridor_ID",
    "Shipping_Lane_ID",
    "Is_Cross_Border"
]

# Dataset structure verification
current_rows = df.shape[0]
current_columns = df.shape[1]

available_engineered_features = [
    column for column in approved_engineered_features
    if column in df.columns
]

missing_engineered_features = [
    column for column in approved_engineered_features
    if column not in df.columns
]

print("FINAL FEATURE ENGINEERING EXPORT VERIFICATION")
print("=" * 80)

print("\nDATASET STRUCTURE")
print("-" * 80)
print(f"Expected Rows: {expected_rows}")
print(f"Current Rows: {current_rows}")
print(f"Row Count Difference: {current_rows - expected_rows}")

print()
print(f"Expected Columns: {expected_columns}")
print(f"Current Columns: {current_columns}")
print(f"Column Count Difference: {current_columns - expected_columns}")

print("\nENGINEERED FEATURE VERIFICATION")
print("-" * 80)
print(f"Expected Engineered Features: {len(approved_engineered_features)}")
print(f"Available Engineered Features: {len(available_engineered_features)}")
print(f"Missing Engineered Features: {len(missing_engineered_features)}")

if missing_engineered_features:
    print("\nMissing Feature Names:")
    for column in missing_engineered_features:
        print(f"- {column}")

print("\nFINAL EXPORT READINESS")
print("-" * 80)

structure_pass = (
    current_rows == expected_rows and
    current_columns == expected_columns
)

features_pass = (
    len(available_engineered_features) == len(approved_engineered_features)
)

if structure_pass and features_pass:
    print("STATUS: PASS")
    print("Feature Engineering dataset is verified successfully.")
    print("All 15 approved engineered features are present.")
    print("Dataset structure matches the STEP 17 locked baseline.")
    print("Dataset is ready for export.")
else:
    print("STATUS: FAIL")
    print("Dataset does not match the expected STEP 17 locked structure.")
    print("Export should not proceed until verification issues are resolved.")

FINAL FEATURE ENGINEERING EXPORT VERIFICATION

DATASET STRUCTURE
--------------------------------------------------------------------------------
Expected Rows: 180519
Current Rows: 180519
Row Count Difference: 0

Expected Columns: 70
Current Columns: 70
Column Count Difference: 0

ENGINEERED FEATURE VERIFICATION
--------------------------------------------------------------------------------
Expected Engineered Features: 15
Available Engineered Features: 15
Missing Engineered Features: 0

FINAL EXPORT READINESS
--------------------------------------------------------------------------------
STATUS: PASS
Feature Engineering dataset is verified successfully.
All 15 approved engineered features are present.
Dataset structure matches the STEP 17 locked baseline.
Dataset is ready for export.


# STEP 18 — EXCEL WORKBOOK ARCHITECTURE AND LOGICAL DATA ORGANIZATION

This section implements the approved professional workbook architecture for the Week 2 Feature Engineered Logistics dataset.

The final Feature Engineering dataset contains:

- 180,519 rows
- 70 total columns
- 55 original cleaned dataset columns
- 15 approved engineered analytical features

Based on the approved workbook architecture review, the dataset will be organized into two logically structured analytical views:

1. Logistic_Master_Business_Data
2. Logistic_ML_Analytics_Ready

The original 70-column Feature Engineered CSV remains preserved as the complete programmatic master dataset.

The workbook architecture implementation will follow these principles:

- No row loss
- No unintended column loss
- Original Feature Engineering dataset remains unchanged
- Order Item Id remains the primary relational key
- Both workbook sheets must preserve identical row alignment
- Business-readable fields and machine learning analytical fields will be logically separated
- Professional column ordering will be applied according to the approved workbook architecture

This step begins with controlled dataset loading and baseline verification before any workbook views or column organization are created.

In [32]:
import pandas as pd
import numpy as np

print("STEP 18.1 — EXCEL WORKBOOK ARCHITECTURE BASELINE VERIFICATION")
print("=" * 80)

expected_rows = 180519
expected_columns = 70

approved_engineered_features = [
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Performance_Category",
    "Delay_Severity_Level",
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Order_Day_of_Week",
    "Is_Weekend_Order",
    "Is_Commercial_Loss",
    "Logistics_Corridor_ID",
    "Shipping_Lane_ID",
    "Is_Cross_Border"
]

print("\nCURRENT DATASET BASELINE")
print("-" * 80)

print(f"Current Dataset Rows: {df.shape[0]}")
print(f"Current Dataset Columns: {df.shape[1]}")

print("\nSTEP 17 LOCKED BASELINE VERIFICATION")
print("-" * 80)

print(f"Expected Rows: {expected_rows}")
print(f"Current Rows: {df.shape[0]}")
print(f"Row Count Difference: {df.shape[0] - expected_rows}")

print()

print(f"Expected Columns: {expected_columns}")
print(f"Current Columns: {df.shape[1]}")
print(f"Column Count Difference: {df.shape[1] - expected_columns}")

print("\nPRIMARY RELATIONAL KEY VERIFICATION")
print("-" * 80)

primary_key = "Order Item Id"

primary_key_available = primary_key in df.columns
primary_key_missing = df[primary_key].isna().sum() if primary_key_available else "N/A"
primary_key_duplicates = (
    df[primary_key].duplicated().sum()
    if primary_key_available
    else "N/A"
)

primary_key_status = (
    "PASS"
    if primary_key_available
    and primary_key_missing == 0
    and primary_key_duplicates == 0
    else "REVIEW REQUIRED"
)

primary_key_verification = pd.DataFrame({
    "Verification Check": [
        "Primary Relational Key",
        "Primary Key Available",
        "Primary Key Missing Values",
        "Duplicate Primary Key Values",
        "Primary Key Integrity Status"
    ],
    "Result": [
        primary_key,
        "YES" if primary_key_available else "NO",
        primary_key_missing,
        primary_key_duplicates,
        primary_key_status
    ]
})

display(primary_key_verification)

print("\nENGINEERED FEATURE BASELINE VERIFICATION")
print("-" * 80)

available_engineered_features = [
    feature for feature in approved_engineered_features
    if feature in df.columns
]

missing_engineered_features = [
    feature for feature in approved_engineered_features
    if feature not in df.columns
]

engineered_feature_verification = pd.DataFrame({
    "Metric": [
        "Expected Engineered Features",
        "Available Engineered Features",
        "Missing Engineered Features"
    ],
    "Value": [
        len(approved_engineered_features),
        len(available_engineered_features),
        len(missing_engineered_features)
    ]
})

display(engineered_feature_verification)

print("\nCOLUMN NAME INTEGRITY")
print("-" * 80)

duplicate_column_count = df.columns.duplicated().sum()

column_integrity = pd.DataFrame({
    "Verification Check": [
        "Duplicate Column Names Detected",
        "Current Dataset Rows",
        "Current Dataset Columns"
    ],
    "Result": [
        duplicate_column_count,
        df.shape[0],
        df.shape[1]
    ]
})

display(column_integrity)

overall_status = (
    "PASS"
    if df.shape[0] == expected_rows
    and df.shape[1] == expected_columns
    and primary_key_available
    and primary_key_missing == 0
    and primary_key_duplicates == 0
    and len(missing_engineered_features) == 0
    and duplicate_column_count == 0
    else "REVIEW REQUIRED"
)

print("\nWORKBOOK ARCHITECTURE READINESS STATUS")
print("-" * 80)

print(f"Overall Baseline Status: {overall_status}")

print("\nSTATUS")
print("-" * 80)

if overall_status == "PASS":
    print("STEP 18.1 baseline verification completed successfully.")
    print("The STEP 17 locked Feature Engineering dataset remains intact.")
    print("Dataset structure is confirmed at 180519 rows and 70 columns.")
    print("All 15 approved engineered features remain available.")
    print("Order Item Id is available and verified as the relational key.")
    print("No duplicate column names were detected.")
    print("No workbook sheets were created in this step.")
    print("No rows were removed.")
    print("No columns were removed.")
    print("No data values were modified.")
    print("Dataset is ready for controlled workbook architecture planning.")
else:
    print("Baseline verification requires review before workbook architecture implementation.")

STEP 18.1 — EXCEL WORKBOOK ARCHITECTURE BASELINE VERIFICATION

CURRENT DATASET BASELINE
--------------------------------------------------------------------------------
Current Dataset Rows: 180519
Current Dataset Columns: 70

STEP 17 LOCKED BASELINE VERIFICATION
--------------------------------------------------------------------------------
Expected Rows: 180519
Current Rows: 180519
Row Count Difference: 0

Expected Columns: 70
Current Columns: 70
Column Count Difference: 0

PRIMARY RELATIONAL KEY VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Primary Relational Key,Order Item Id
1,Primary Key Available,YES
2,Primary Key Missing Values,0
3,Duplicate Primary Key Values,0
4,Primary Key Integrity Status,PASS



ENGINEERED FEATURE BASELINE VERIFICATION
--------------------------------------------------------------------------------


,Metric,Value
0,Expected Engineered Features,15
1,Available Engineered Features,15
2,Missing Engineered Features,0



COLUMN NAME INTEGRITY
--------------------------------------------------------------------------------


,Verification Check,Result
0,Duplicate Column Names Detected,0
1,Current Dataset Rows,180519
2,Current Dataset Columns,70



WORKBOOK ARCHITECTURE READINESS STATUS
--------------------------------------------------------------------------------
Overall Baseline Status: PASS

STATUS
--------------------------------------------------------------------------------
STEP 18.1 baseline verification completed successfully.
The STEP 17 locked Feature Engineering dataset remains intact.
Dataset structure is confirmed at 180519 rows and 70 columns.
All 15 approved engineered features remain available.
Order Item Id is available and verified as the relational key.
No duplicate column names were detected.
No workbook sheets were created in this step.
No rows were removed.
No columns were removed.
No data values were modified.
Dataset is ready for controlled workbook architecture planning.


# STEP 18.2 — PROFESSIONAL COLUMN CLASSIFICATION AND WORKBOOK SHEET ARCHITECTURE PLANNING

This step defines the approved logical column architecture for the Week 2 Feature Engineered Logistics dataset before creating any Excel workbook sheets.

The 70-column Feature Engineering dataset will remain unchanged.

Two professional analytical workbook views will be planned:

1. Logistic_Master_Business_Data
2. Logistic_ML_Analytics_Ready

The workbook architecture will use Order Item Id as the common relational key between analytical views.

This step performs controlled column classification and architecture verification only.

The objectives are to:

- Define the professional business-oriented column structure
- Define the dedicated analytics and machine learning column structure
- Verify all planned columns exist in the locked 70-column dataset
- Verify no unintended columns are omitted from the master business structure
- Verify the relational key is included where required
- Establish the approved sheet architecture before physical workbook creation

No Excel workbook will be created in this step.
No dataset values will be modified.
No rows will be removed.
No source columns will be removed.

In [33]:
print("STEP 18.2 — PROFESSIONAL COLUMN CLASSIFICATION & WORKBOOK SHEET ARCHITECTURE PLANNING")
print("=" * 80)

print("\nAPPROVED WORKBOOK SHEET ARCHITECTURE")
print("-" * 80)

workbook_architecture = pd.DataFrame({
    "Workbook Sheet": [
        "Logistic_Master_Business_Data",
        "Logistic_ML_Analytics_Ready"
    ],
    "Purpose": [
        "Primary business, operational, commercial and logistics analysis view",
        "Dedicated analytics and machine learning ready view"
    ],
    "Common Relational Key": [
        "Order Item Id",
        "Order Item Id"
    ]
})

display(workbook_architecture)

print("\nMASTER BUSINESS DATA COLUMN CLASSIFICATION")
print("-" * 80)

master_business_columns = [
    "Order Item Id",
    "Order Id",
    "Order Customer Id",
    "Customer Id",
    "Customer Fname",
    "Customer Lname",
    "Customer Segment",
    "Customer City",
    "Customer State",
    "Customer Country",
    "Customer Zipcode",
    "Customer Street",
    "Latitude",
    "Longitude",
    "Order City",
    "Order State",
    "Order Country",
    "Order Region",
    "Order Zipcode",
    "Market",
    "Type",
    "Category Id",
    "Category Name",
    "Department Id",
    "Department Name",
    "Product Card Id",
    "Product Category Id",
    "Product Description",
    "Product Image",
    "Product Name",
    "Product Price",
    "Order Item Cardprod Id",
    "Order Item Category Id",
    "Order Item Discount",
    "Order Item Discount Rate",
    "Order Item Product Price",
    "Order Item Profit Ratio",
    "Order Item Quantity",
    "Sales",
    "Order Item Total",
    "Benefit per order",
    "Order Status",
    "Shipping Mode",
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Late_delivery_risk",
    "order date (DateOrders)",
    "shipping date (DateOrders)",
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Performance_Category",
    "Delay_Severity_Level",
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Order_Day_of_Week",
    "Is_Weekend_Order",
    "Is_Commercial_Loss",
    "Logistics_Corridor_ID",
    "Shipping_Lane_ID",
    "Is_Cross_Border"
]

print(f"Planned Master Business Columns: {len(master_business_columns)}")

print("\nML AND ANALYTICS READY COLUMN CLASSIFICATION")
print("-" * 80)

ml_analytics_columns = [
    "Order Item Id",
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Performance_Category",
    "Delay_Severity_Level",
    "Order_Year",
    "Order_Month",
    "Order_Day_of_Week",
    "Is_Weekend_Order",
    "Is_Commercial_Loss",
    "Logistics_Corridor_ID",
    "Shipping_Lane_ID",
    "Is_Cross_Border",
    "Late_delivery_risk"
]

print(f"Planned ML Analytics Ready Columns: {len(ml_analytics_columns)}")

print("\nMASTER BUSINESS COLUMN AVAILABILITY VERIFICATION")
print("-" * 80)

missing_master_columns = [
    column for column in master_business_columns
    if column not in df.columns
]

master_availability = pd.DataFrame({
    "Metric": [
        "Planned Master Business Columns",
        "Available Master Business Columns",
        "Missing Master Business Columns"
    ],
    "Value": [
        len(master_business_columns),
        len(master_business_columns) - len(missing_master_columns),
        len(missing_master_columns)
    ]
})

display(master_availability)

print("\nML ANALYTICS COLUMN AVAILABILITY VERIFICATION")
print("-" * 80)

missing_ml_columns = [
    column for column in ml_analytics_columns
    if column not in df.columns
]

ml_availability = pd.DataFrame({
    "Metric": [
        "Planned ML Analytics Columns",
        "Available ML Analytics Columns",
        "Missing ML Analytics Columns"
    ],
    "Value": [
        len(ml_analytics_columns),
        len(ml_analytics_columns) - len(missing_ml_columns),
        len(missing_ml_columns)
    ]
})

display(ml_availability)

print("\nRELATIONAL KEY ARCHITECTURE VERIFICATION")
print("-" * 80)

relational_key = "Order Item Id"

key_architecture = pd.DataFrame({
    "Verification Check": [
        "Relational Key Defined",
        "Key Present in Master Business Architecture",
        "Key Present in ML Analytics Architecture"
    ],
    "Result": [
        relational_key,
        "YES" if relational_key in master_business_columns else "NO",
        "YES" if relational_key in ml_analytics_columns else "NO"
    ]
})

display(key_architecture)

print("\nDATASET COLUMN COVERAGE VERIFICATION")
print("-" * 80)

master_columns_not_in_dataset = [
    column for column in master_business_columns
    if column not in df.columns
]

unassigned_dataset_columns = [
    column for column in df.columns
    if column not in master_business_columns
]

coverage_verification = pd.DataFrame({
    "Verification Check": [
        "Total Locked Dataset Columns",
        "Columns Assigned to Master Business Architecture",
        "Dataset Columns Not Assigned to Master Business Architecture",
        "Missing Planned Master Columns"
    ],
    "Result": [
        len(df.columns),
        len(master_business_columns),
        len(unassigned_dataset_columns),
        len(master_columns_not_in_dataset)
    ]
})

display(coverage_verification)

overall_architecture_status = (
    "PASS"
    if len(missing_master_columns) == 0
    and len(missing_ml_columns) == 0
    and relational_key in master_business_columns
    and relational_key in ml_analytics_columns
    else "REVIEW REQUIRED"
)

print("\nWORKBOOK ARCHITECTURE PLANNING STATUS")
print("-" * 80)

print(f"Overall Architecture Planning Status: {overall_architecture_status}")

print("\nSTATUS")
print("-" * 80)

if overall_architecture_status == "PASS":
    print("STEP 18.2 workbook architecture planning completed successfully.")
    print("Both workbook views have been logically defined.")
    print("All planned columns are available in the locked Feature Engineering dataset.")
    print("Order Item Id is confirmed as the common relational key.")
    print("No dataset values were modified.")
    print("No rows were removed.")
    print("No dataset columns were removed.")
    print("No Excel workbook sheets were created in this step.")
    print("Dataset is ready for controlled professional column ordering and sheet construction.")
else:
    print("Workbook architecture planning requires review before proceeding.")

STEP 18.2 — PROFESSIONAL COLUMN CLASSIFICATION & WORKBOOK SHEET ARCHITECTURE PLANNING

APPROVED WORKBOOK SHEET ARCHITECTURE
--------------------------------------------------------------------------------


,Workbook Sheet,Purpose,Common Relational Key
0,Logistic_Master_Business_Data,"Primary business, operational, commercial and ...",Order Item Id
1,Logistic_ML_Analytics_Ready,Dedicated analytics and machine learning ready...,Order Item Id



MASTER BUSINESS DATA COLUMN CLASSIFICATION
--------------------------------------------------------------------------------
Planned Master Business Columns: 63

ML AND ANALYTICS READY COLUMN CLASSIFICATION
--------------------------------------------------------------------------------
Planned ML Analytics Ready Columns: 16

MASTER BUSINESS COLUMN AVAILABILITY VERIFICATION
--------------------------------------------------------------------------------


,Metric,Value
0,Planned Master Business Columns,63
1,Available Master Business Columns,56
2,Missing Master Business Columns,7



ML ANALYTICS COLUMN AVAILABILITY VERIFICATION
--------------------------------------------------------------------------------


,Metric,Value
0,Planned ML Analytics Columns,16
1,Available ML Analytics Columns,15
2,Missing ML Analytics Columns,1



RELATIONAL KEY ARCHITECTURE VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Relational Key Defined,Order Item Id
1,Key Present in Master Business Architecture,YES
2,Key Present in ML Analytics Architecture,YES



DATASET COLUMN COVERAGE VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Total Locked Dataset Columns,70
1,Columns Assigned to Master Business Architecture,63
2,Dataset Columns Not Assigned to Master Busines...,14
3,Missing Planned Master Columns,7



WORKBOOK ARCHITECTURE PLANNING STATUS
--------------------------------------------------------------------------------
Overall Architecture Planning Status: REVIEW REQUIRED

STATUS
--------------------------------------------------------------------------------
Workbook architecture planning requires review before proceeding.


# STEP 18.2A — ACTUAL DATASET COLUMN AUDIT AND ARCHITECTURE MISMATCH REVIEW

The initial workbook architecture planning verification identified column mismatches between the proposed sheet architecture and the actual locked 70-column Feature Engineering dataset.

This review step will inspect the exact current dataset column names and identify:

- Planned Master Business columns not available in the dataset
- Planned ML Analytics columns not available in the dataset
- Actual dataset columns not assigned to the proposed Master Business architecture
- Exact column naming differences requiring controlled architecture correction

No workbook sheets will be created in this step.

No dataset values will be modified.
No rows will be removed.
No columns will be removed.
No column names will be changed.

The purpose of this step is to correct the workbook architecture planning register using the actual locked dataset structure before proceeding.

In [34]:
print("STEP 18.2A — ACTUAL DATASET COLUMN AUDIT & ARCHITECTURE MISMATCH REVIEW")
print("=" * 80)

actual_dataset_columns = pd.Index(df.columns)

missing_master_columns = pd.Index(master_business_columns).difference(actual_dataset_columns)

missing_ml_columns = pd.Index(ml_analytics_columns).difference(actual_dataset_columns)

unassigned_dataset_columns = actual_dataset_columns.difference(
    pd.Index(master_business_columns)
)

print("\nACTUAL LOCKED DATASET COLUMN REGISTER")
print("-" * 80)

actual_column_register = pd.DataFrame({
    "Column Number": range(1, len(df.columns) + 1),
    "Actual Dataset Column": df.columns
})

display(actual_column_register)

print("\nMASTER BUSINESS ARCHITECTURE MISMATCH")
print("-" * 80)

missing_master_register = pd.DataFrame({
    "Planned Master Column Not Found": missing_master_columns
})

print(f"Missing Master Business Columns: {len(missing_master_columns)}")

display(missing_master_register)

print("\nML ANALYTICS ARCHITECTURE MISMATCH")
print("-" * 80)

missing_ml_register = pd.DataFrame({
    "Planned ML Analytics Column Not Found": missing_ml_columns
})

print(f"Missing ML Analytics Columns: {len(missing_ml_columns)}")

display(missing_ml_register)

print("\nACTUAL DATASET COLUMNS NOT ASSIGNED TO MASTER ARCHITECTURE")
print("-" * 80)

unassigned_column_register = pd.DataFrame({
    "Actual Dataset Column Not Assigned": unassigned_dataset_columns
})

print(f"Unassigned Actual Dataset Columns: {len(unassigned_dataset_columns)}")

display(unassigned_column_register)

print("\nCOLUMN ARCHITECTURE AUDIT SUMMARY")
print("-" * 80)

audit_summary = pd.DataFrame({
    "Metric": [
        "Total Actual Dataset Columns",
        "Proposed Master Business Columns",
        "Master Columns Available",
        "Master Columns Missing",
        "Proposed ML Analytics Columns",
        "ML Analytics Columns Available",
        "ML Analytics Columns Missing",
        "Actual Dataset Columns Not Assigned to Master"
    ],
    "Value": [
        len(actual_dataset_columns),
        len(master_business_columns),
        len(master_business_columns) - len(missing_master_columns),
        len(missing_master_columns),
        len(ml_analytics_columns),
        len(ml_analytics_columns) - len(missing_ml_columns),
        len(missing_ml_columns),
        len(unassigned_dataset_columns)
    ]
})

display(audit_summary)

print("\nSTATUS")
print("-" * 80)
print("Actual dataset column audit completed.")
print("No dataset modifications were performed.")
print("No rows were removed.")
print("No columns were removed.")
print("No column names were changed.")
print("Workbook architecture implementation remains on hold pending controlled review.")

STEP 18.2A — ACTUAL DATASET COLUMN AUDIT & ARCHITECTURE MISMATCH REVIEW

ACTUAL LOCKED DATASET COLUMN REGISTER
--------------------------------------------------------------------------------


,Column Number,Actual Dataset Column
0,1,Type
1,2,Days for shipping (real)
2,3,Days for shipment (scheduled)
3,4,Benefit per order
4,5,Delivery Status
...,...,...
65,66,Is_Weekend_Order
66,67,Is_Commercial_Loss
67,68,Logistics_Corridor_ID
68,69,Shipping_Lane_ID



MASTER BUSINESS ARCHITECTURE MISMATCH
--------------------------------------------------------------------------------
Missing Master Business Columns: 7


,Planned Master Column Not Found
0,Late_delivery_risk
1,Order Customer Id
2,Order Item Cardprod Id
3,Order Item Category Id
4,Product Category Id
5,Product Image
6,Product Price



ML ANALYTICS ARCHITECTURE MISMATCH
--------------------------------------------------------------------------------
Missing ML Analytics Columns: 1


,Planned ML Analytics Column Not Found
0,Late_delivery_risk



ACTUAL DATASET COLUMNS NOT ASSIGNED TO MASTER ARCHITECTURE
--------------------------------------------------------------------------------
Unassigned Actual Dataset Columns: 14


,Actual Dataset Column Not Assigned
0,Benefit per order_scaled
1,Customer Email
2,Days for shipment (scheduled)_scaled
3,Days for shipping (real)_scaled
4,Delivery Status
5,Late delivery risk
6,Order Item Discount Rate_scaled
7,Order Item Discount_scaled
8,Order Item Product Price_scaled
9,Order Item Profit Ratio_scaled



COLUMN ARCHITECTURE AUDIT SUMMARY
--------------------------------------------------------------------------------


,Metric,Value
0,Total Actual Dataset Columns,70
1,Proposed Master Business Columns,63
2,Master Columns Available,56
3,Master Columns Missing,7
4,Proposed ML Analytics Columns,16
5,ML Analytics Columns Available,15
6,ML Analytics Columns Missing,1
7,Actual Dataset Columns Not Assigned to Master,14



STATUS
--------------------------------------------------------------------------------
Actual dataset column audit completed.
No dataset modifications were performed.
No rows were removed.
No columns were removed.
No column names were changed.
Workbook architecture implementation remains on hold pending controlled review.


# STEP 18.2B — CORRECTED WORKBOOK ARCHITECTURE AND COLUMN ALLOCATION VERIFICATION

This step corrects the workbook column architecture using the actual locked 70-column Feature Engineering dataset and the approved Excel Workbook Architecture Review.

The approved workbook structure consists of:

1. Logistic_Master_Business_Data — 59 columns
2. Logistic_ML_Analytics_Ready — 16 columns

The Master Business Data view contains all approved non-scaled business, operational, commercial, logistics, performance and temporal fields.

The ML Analytics Ready view contains the approved analytical targets, standardized numerical features, Shipping Mode and Logistics_Corridor_ID.

Order Zipcode_scaled remains retained in the original 70-column master dataset but is excluded from the approved ML Analytics Ready worksheet.

Order Item Id remains the common relational key between both workbook sheets.

This step performs corrected column allocation verification only.

No Excel workbook will be created in this step.
No dataset values will be modified.
No rows will be removed.
No source columns will be removed.
No column names will be changed.

In [35]:
print("STEP 18.2B — CORRECTED WORKBOOK ARCHITECTURE & COLUMN ALLOCATION VERIFICATION")
print("=" * 80)

print("\nAPPROVED WORKBOOK ARCHITECTURE")
print("-" * 80)

approved_scaled_columns = [
    "Days for shipping (real)_scaled",
    "Days for shipment (scheduled)_scaled",
    "Benefit per order_scaled",
    "Order Item Discount_scaled",
    "Order Item Discount Rate_scaled",
    "Order Item Product Price_scaled",
    "Order Item Profit Ratio_scaled",
    "Order Item Quantity_scaled",
    "Sales_scaled",
    "Order Item Total_scaled",
    "Order Zipcode_scaled"
]

master_business_columns = [
    column for column in df.columns
    if column not in approved_scaled_columns
]

ml_analytics_columns = [
    "Order Item Id",
    "Delivery_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Days for shipping (real)_scaled",
    "Days for shipment (scheduled)_scaled",
    "Benefit per order_scaled",
    "Order Item Discount_scaled",
    "Order Item Discount Rate_scaled",
    "Order Item Product Price_scaled",
    "Order Item Profit Ratio_scaled",
    "Order Item Quantity_scaled",
    "Sales_scaled",
    "Order Item Total_scaled",
    "Shipping Mode",
    "Logistics_Corridor_ID"
]

workbook_architecture = pd.DataFrame({
    "Workbook Sheet": [
        "Logistic_Master_Business_Data",
        "Logistic_ML_Analytics_Ready"
    ],
    "Expected Columns": [
        59,
        16
    ],
    "Actual Planned Columns": [
        len(master_business_columns),
        len(ml_analytics_columns)
    ],
    "Primary Relational Key": [
        "Order Item Id",
        "Order Item Id"
    ]
})

display(workbook_architecture)

print("\nMASTER BUSINESS DATA COLUMN VERIFICATION")
print("-" * 80)

missing_master_columns = [
    column for column in master_business_columns
    if column not in df.columns
]

master_scaled_columns_detected = [
    column for column in master_business_columns
    if column.endswith("_scaled")
]

master_verification = pd.DataFrame({
    "Metric": [
        "Expected Master Business Columns",
        "Planned Master Business Columns",
        "Missing Master Business Columns",
        "Scaled Columns Included in Master"
    ],
    "Value": [
        59,
        len(master_business_columns),
        len(missing_master_columns),
        len(master_scaled_columns_detected)
    ]
})

display(master_verification)

print("\nML ANALYTICS READY COLUMN VERIFICATION")
print("-" * 80)

missing_ml_columns = [
    column for column in ml_analytics_columns
    if column not in df.columns
]

ml_verification = pd.DataFrame({
    "Metric": [
        "Expected ML Analytics Columns",
        "Planned ML Analytics Columns",
        "Available ML Analytics Columns",
        "Missing ML Analytics Columns"
    ],
    "Value": [
        16,
        len(ml_analytics_columns),
        len(ml_analytics_columns) - len(missing_ml_columns),
        len(missing_ml_columns)
    ]
})

display(ml_verification)

print("\nSCALED FEATURE ALLOCATION VERIFICATION")
print("-" * 80)

scaled_feature_allocation = pd.DataFrame({
    "Scaled Feature": approved_scaled_columns,
    "Available in Dataset": [
        "YES" if column in df.columns else "NO"
        for column in approved_scaled_columns
    ],
    "Workbook Allocation": [
        "ML Analytics Ready"
        if column != "Order Zipcode_scaled"
        else "Excluded from ML Analytics Ready"
        for column in approved_scaled_columns
    ]
})

display(scaled_feature_allocation)

print("\nRELATIONAL KEY VERIFICATION")
print("-" * 80)

relational_key = "Order Item Id"

key_verification = pd.DataFrame({
    "Verification Check": [
        "Primary Relational Key",
        "Available in Dataset",
        "Present in Master Business Data",
        "Present in ML Analytics Ready"
    ],
    "Result": [
        relational_key,
        "YES" if relational_key in df.columns else "NO",
        "YES" if relational_key in master_business_columns else "NO",
        "YES" if relational_key in ml_analytics_columns else "NO"
    ]
})

display(key_verification)

print("\nDATASET ALLOCATION COVERAGE VERIFICATION")
print("-" * 80)

expected_master_columns = 59
expected_ml_columns = 16

excluded_from_master = [
    column for column in df.columns
    if column not in master_business_columns
]

expected_master_exclusions = approved_scaled_columns

unexpected_master_exclusions = [
    column for column in excluded_from_master
    if column not in expected_master_exclusions
]

allocation_verification = pd.DataFrame({
    "Verification Check": [
        "Total Locked Dataset Columns",
        "Expected Master Business Columns",
        "Actual Master Business Columns",
        "Expected Scaled Columns Outside Master",
        "Actual Columns Outside Master",
        "Unexpected Master Exclusions",
        "Expected ML Analytics Columns",
        "Actual ML Analytics Columns"
    ],
    "Result": [
        len(df.columns),
        expected_master_columns,
        len(master_business_columns),
        len(approved_scaled_columns),
        len(excluded_from_master),
        len(unexpected_master_exclusions),
        expected_ml_columns,
        len(ml_analytics_columns)
    ]
})

display(allocation_verification)

overall_architecture_status = (
    "PASS"
    if len(master_business_columns) == expected_master_columns
    and len(missing_master_columns) == 0
    and len(master_scaled_columns_detected) == 0
    and len(ml_analytics_columns) == expected_ml_columns
    and len(missing_ml_columns) == 0
    and len(unexpected_master_exclusions) == 0
    and relational_key in master_business_columns
    and relational_key in ml_analytics_columns
    else "REVIEW REQUIRED"
)

print("\nCORRECTED WORKBOOK ARCHITECTURE STATUS")
print("-" * 80)

print(f"Overall Architecture Status: {overall_architecture_status}")

print("\nSTATUS")
print("-" * 80)

if overall_architecture_status == "PASS":
    print("STEP 18.2B corrected workbook architecture verification completed successfully.")
    print("Logistic_Master_Business_Data architecture verified at 59 columns.")
    print("Logistic_ML_Analytics_Ready architecture verified at 16 columns.")
    print("All approved ML Analytics Ready columns are available.")
    print("All scaled feature allocations were verified.")
    print("Order Zipcode_scaled remains excluded from the ML Analytics Ready sheet.")
    print("Order Item Id is confirmed as the common relational key.")
    print("No dataset values were modified.")
    print("No rows were removed.")
    print("No source columns were removed.")
    print("No Excel workbook sheets were created in this step.")
    print("Dataset is ready for professional column ordering.")
else:
    print("Corrected workbook architecture requires review before proceeding.")

STEP 18.2B — CORRECTED WORKBOOK ARCHITECTURE & COLUMN ALLOCATION VERIFICATION

APPROVED WORKBOOK ARCHITECTURE
--------------------------------------------------------------------------------


,Workbook Sheet,Expected Columns,Actual Planned Columns,Primary Relational Key
0,Logistic_Master_Business_Data,59,59,Order Item Id
1,Logistic_ML_Analytics_Ready,16,16,Order Item Id



MASTER BUSINESS DATA COLUMN VERIFICATION
--------------------------------------------------------------------------------


,Metric,Value
0,Expected Master Business Columns,59
1,Planned Master Business Columns,59
2,Missing Master Business Columns,0
3,Scaled Columns Included in Master,0



ML ANALYTICS READY COLUMN VERIFICATION
--------------------------------------------------------------------------------


,Metric,Value
0,Expected ML Analytics Columns,16
1,Planned ML Analytics Columns,16
2,Available ML Analytics Columns,16
3,Missing ML Analytics Columns,0



SCALED FEATURE ALLOCATION VERIFICATION
--------------------------------------------------------------------------------


,Scaled Feature,Available in Dataset,Workbook Allocation
0,Days for shipping (real)_scaled,YES,ML Analytics Ready
1,Days for shipment (scheduled)_scaled,YES,ML Analytics Ready
2,Benefit per order_scaled,YES,ML Analytics Ready
3,Order Item Discount_scaled,YES,ML Analytics Ready
4,Order Item Discount Rate_scaled,YES,ML Analytics Ready
5,Order Item Product Price_scaled,YES,ML Analytics Ready
6,Order Item Profit Ratio_scaled,YES,ML Analytics Ready
7,Order Item Quantity_scaled,YES,ML Analytics Ready
8,Sales_scaled,YES,ML Analytics Ready
9,Order Item Total_scaled,YES,ML Analytics Ready



RELATIONAL KEY VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Primary Relational Key,Order Item Id
1,Available in Dataset,YES
2,Present in Master Business Data,YES
3,Present in ML Analytics Ready,YES



DATASET ALLOCATION COVERAGE VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Total Locked Dataset Columns,70
1,Expected Master Business Columns,59
2,Actual Master Business Columns,59
3,Expected Scaled Columns Outside Master,11
4,Actual Columns Outside Master,11
5,Unexpected Master Exclusions,0
6,Expected ML Analytics Columns,16
7,Actual ML Analytics Columns,16



CORRECTED WORKBOOK ARCHITECTURE STATUS
--------------------------------------------------------------------------------
Overall Architecture Status: PASS

STATUS
--------------------------------------------------------------------------------
STEP 18.2B corrected workbook architecture verification completed successfully.
Logistic_Master_Business_Data architecture verified at 59 columns.
Logistic_ML_Analytics_Ready architecture verified at 16 columns.
All approved ML Analytics Ready columns are available.
All scaled feature allocations were verified.
Order Zipcode_scaled remains excluded from the ML Analytics Ready sheet.
Order Item Id is confirmed as the common relational key.
No dataset values were modified.
No rows were removed.
No source columns were removed.
No Excel workbook sheets were created in this step.
Dataset is ready for professional column ordering.


# STEP 18.3 — PROFESSIONAL COLUMN ORDERING DESIGN & VERIFICATION

This step defines and verifies the professional column order for the approved Excel workbook architecture.

The column order is designed to improve business readability, analytical usability and logical data navigation.

The approved workbook views remain:

1. Logistic_Master_Business_Data — 59 columns
2. Logistic_ML_Analytics_Ready — 16 columns

The Master Business Data sheet will organize columns into logical business and operational groups.

The ML Analytics Ready sheet will organize columns according to relational identification, analytical targets, standardized numerical features and approved operational features.

This step performs column ordering design and verification only.

No Excel workbook will be created in this step.
No dataset values will be modified.
No rows will be removed.
No columns will be removed.
No column names will be changed.

In [36]:
print("STEP 18.3 — PROFESSIONAL COLUMN ORDERING DESIGN & VERIFICATION")
print("=" * 80)

# ------------------------------------------------------------
# MASTER BUSINESS DATA PROFESSIONAL COLUMN ORDER
# ------------------------------------------------------------

master_column_groups = {

    "1. IDENTIFIERS AND TRANSACTION KEYS": [
        "Order Item Id",
        "Order Id",
        "Customer Id"
    ],

    "2. CUSTOMER INFORMATION": [
        "Customer Fname",
        "Customer Lname",
        "Customer Email",
        "Customer City",
        "Customer State",
        "Customer Country",
        "Customer Zipcode",
        "Customer Segment"
    ],

    "3. PRODUCT AND CATEGORY INFORMATION": [
        "Product Name",
        "Category Name",
        "Department Name"
    ],

    "4. ORDER AND SHIPPING INFORMATION": [
        "Type",
        "Order Status",
        "Shipping Mode",
        "Delivery Status",
        "Late delivery risk"
    ],

    "5. GEOGRAPHIC AND MARKET INFORMATION": [
        "Market",
        "Order Region",
        "Order City",
        "Order State",
        "Order Country",
        "Order Zipcode",
        "Order Latitude",
        "Order Longitude"
    ],

    "6. FINANCIAL AND COMMERCIAL METRICS": [
        "Benefit per order",
        "Sales",
        "Order Item Total",
        "Order Item Product Price",
        "Order Item Discount",
        "Order Item Discount Rate",
        "Order Item Profit Ratio",
        "Order Item Quantity"
    ],

    "7. OPERATIONAL AND DELIVERY METRICS": [
        "Days for shipping (real)",
        "Days for shipment (scheduled)",
        "Delivery_Time_Hours",
        "Promised_Time_Hours",
        "Delay_Hours"
    ],

    "8. DATE AND TEMPORAL INFORMATION": [
        "order date (DateOrders)",
        "shipping date (DateOrders)",
        "Order_Year",
        "Order_Month",
        "Order_Month_Name",
        "Order_Day_of_Week",
        "Is_Weekend_Order"
    ],

    "9. PERFORMANCE AND COMMERCIAL INDICATORS": [
        "Delay_Flag",
        "Performance_Category",
        "Delay_Severity_Level",
        "Is_Commercial_Loss"
    ],

    "10. LOGISTICS ENGINEERED FEATURES": [
        "Logistics_Corridor_ID",
        "Shipping_Lane_ID",
        "Is_Cross_Border"
    ]
}


professional_master_order = []

for group_columns in master_column_groups.values():
    professional_master_order.extend(group_columns)


# ------------------------------------------------------------
# ML ANALYTICS READY PROFESSIONAL COLUMN ORDER
# ------------------------------------------------------------

professional_ml_order = [

    "Order Item Id",

    "Delay_Flag",
    "Delay_Hours",

    "Days for shipping (real)_scaled",
    "Days for shipment (scheduled)_scaled",
    "Benefit per order_scaled",
    "Order Item Discount_scaled",
    "Order Item Discount Rate_scaled",
    "Order Item Product Price_scaled",
    "Order Item Profit Ratio_scaled",
    "Order Item Quantity_scaled",
    "Sales_scaled",
    "Order Item Total_scaled",

    "Shipping Mode",
    "Logistics_Corridor_ID"
]


print("\nMASTER BUSINESS DATA COLUMN GROUPING")
print("-" * 80)

master_group_register = []

for group_name, columns in master_column_groups.items():

    for position, column in enumerate(columns, start=1):

        master_group_register.append({
            "Column Group": group_name,
            "Group Position": position,
            "Column Name": column
        })

master_group_df = pd.DataFrame(master_group_register)

display(master_group_df)


print("\nMASTER BUSINESS COLUMN ORDER VERIFICATION")
print("-" * 80)

missing_master_order_columns = [
    column for column in professional_master_order
    if column not in df.columns
]

duplicate_master_order_columns = [
    column for column in professional_master_order
    if professional_master_order.count(column) > 1
]

actual_master_columns_not_ordered = [
    column for column in master_business_columns
    if column not in professional_master_order
]

master_order_verification = pd.DataFrame({
    "Verification Check": [
        "Expected Master Business Columns",
        "Professional Master Order Columns",
        "Missing Columns in Dataset",
        "Duplicate Columns in Order",
        "Actual Master Columns Not Ordered"
    ],
    "Result": [
        len(master_business_columns),
        len(professional_master_order),
        len(missing_master_order_columns),
        len(set(duplicate_master_order_columns)),
        len(actual_master_columns_not_ordered)
    ]
})

display(master_order_verification)


print("\nML ANALYTICS READY COLUMN ORDER")
print("-" * 80)

ml_order_df = pd.DataFrame({
    "Column Position": range(1, len(professional_ml_order) + 1),
    "Column Name": professional_ml_order
})

display(ml_order_df)


print("\nML ANALYTICS COLUMN ORDER VERIFICATION")
print("-" * 80)

missing_ml_order_columns = [
    column for column in professional_ml_order
    if column not in df.columns
]

duplicate_ml_order_columns = [
    column for column in professional_ml_order
    if professional_ml_order.count(column) > 1
]

approved_ml_columns_not_ordered = [
    column for column in ml_analytics_columns
    if column not in professional_ml_order
]

unexpected_ml_order_columns = [
    column for column in professional_ml_order
    if column not in ml_analytics_columns
]

ml_order_verification = pd.DataFrame({
    "Verification Check": [
        "Expected ML Analytics Columns",
        "Professional ML Order Columns",
        "Missing Columns in Dataset",
        "Duplicate Columns in Order",
        "Approved ML Columns Not Ordered",
        "Unexpected ML Order Columns"
    ],
    "Result": [
        len(ml_analytics_columns),
        len(professional_ml_order),
        len(missing_ml_order_columns),
        len(set(duplicate_ml_order_columns)),
        len(approved_ml_columns_not_ordered),
        len(unexpected_ml_order_columns)
    ]
})

display(ml_order_verification)


master_order_status = (
    "PASS"
    if len(professional_master_order) == len(master_business_columns)
    and len(missing_master_order_columns) == 0
    and len(set(duplicate_master_order_columns)) == 0
    and len(actual_master_columns_not_ordered) == 0
    else "REVIEW REQUIRED"
)

ml_order_status = (
    "PASS"
    if len(professional_ml_order) == len(ml_analytics_columns)
    and len(missing_ml_order_columns) == 0
    and len(set(duplicate_ml_order_columns)) == 0
    and len(approved_ml_columns_not_ordered) == 0
    and len(unexpected_ml_order_columns) == 0
    else "REVIEW REQUIRED"
)


print("\nFINAL COLUMN ORDERING STATUS")
print("-" * 80)

print(f"Master Business Data Column Order Status: {master_order_status}")
print(f"ML Analytics Ready Column Order Status: {ml_order_status}")


overall_order_status = (
    "PASS"
    if master_order_status == "PASS"
    and ml_order_status == "PASS"
    else "REVIEW REQUIRED"
)

print(f"Overall Professional Column Ordering Status: {overall_order_status}")


print("\nSTATUS")
print("-" * 80)

if overall_order_status == "PASS":

    print("STEP 18.3 professional column ordering completed successfully.")
    print("Master Business Data professional order verified.")
    print("ML Analytics Ready professional order verified.")
    print("All approved columns are assigned exactly once within their respective views.")
    print("No unexpected columns were included.")
    print("No approved columns were omitted.")
    print("No dataset values were modified.")
    print("No rows were removed.")
    print("No columns were removed.")
    print("No Excel workbook sheets were created in this step.")
    print("Dataset is ready for controlled workbook view construction.")

else:

    print("Professional column ordering requires review before proceeding.")

STEP 18.3 — PROFESSIONAL COLUMN ORDERING DESIGN & VERIFICATION

MASTER BUSINESS DATA COLUMN GROUPING
--------------------------------------------------------------------------------


,Column Group,Group Position,Column Name
0,1. IDENTIFIERS AND TRANSACTION KEYS,1,Order Item Id
1,1. IDENTIFIERS AND TRANSACTION KEYS,2,Order Id
2,1. IDENTIFIERS AND TRANSACTION KEYS,3,Customer Id
3,2. CUSTOMER INFORMATION,1,Customer Fname
4,2. CUSTOMER INFORMATION,2,Customer Lname
5,2. CUSTOMER INFORMATION,3,Customer Email
6,2. CUSTOMER INFORMATION,4,Customer City
7,2. CUSTOMER INFORMATION,5,Customer State
8,2. CUSTOMER INFORMATION,6,Customer Country
9,2. CUSTOMER INFORMATION,7,Customer Zipcode



MASTER BUSINESS COLUMN ORDER VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Expected Master Business Columns,59
1,Professional Master Order Columns,54
2,Missing Columns in Dataset,2
3,Duplicate Columns in Order,0
4,Actual Master Columns Not Ordered,7



ML ANALYTICS READY COLUMN ORDER
--------------------------------------------------------------------------------


,Column Position,Column Name
0,1,Order Item Id
1,2,Delay_Flag
2,3,Delay_Hours
3,4,Days for shipping (real)_scaled
4,5,Days for shipment (scheduled)_scaled
5,6,Benefit per order_scaled
6,7,Order Item Discount_scaled
7,8,Order Item Discount Rate_scaled
8,9,Order Item Product Price_scaled
9,10,Order Item Profit Ratio_scaled



ML ANALYTICS COLUMN ORDER VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Expected ML Analytics Columns,16
1,Professional ML Order Columns,15
2,Missing Columns in Dataset,0
3,Duplicate Columns in Order,0
4,Approved ML Columns Not Ordered,1
5,Unexpected ML Order Columns,0



FINAL COLUMN ORDERING STATUS
--------------------------------------------------------------------------------
Master Business Data Column Order Status: REVIEW REQUIRED
ML Analytics Ready Column Order Status: REVIEW REQUIRED
Overall Professional Column Ordering Status: REVIEW REQUIRED

STATUS
--------------------------------------------------------------------------------
Professional column ordering requires review before proceeding.


# STEP 18.3A — PROFESSIONAL COLUMN ORDERING CORRECTION & RE-VERIFICATION

This step corrects and re-verifies the professional column ordering architecture identified during STEP 18.3 review.

The locked STEP 17 Feature Engineering dataset remains unchanged.

Objectives:
- Re-verify the approved 59-column Master Business Data architecture.
- Re-verify the approved 16-column ML Analytics Ready architecture.
- Ensure every approved ML Analytics Ready column is included in the professional ordering list.
- Identify and eliminate any column ordering mismatch.
- Confirm that no dataset values, rows, or columns are modified.

This is a controlled architecture verification step only.
No Excel workbook sheets are created in this step.

In [37]:
import pandas as pd

print("STEP 18.3A — PROFESSIONAL COLUMN ORDERING CORRECTION & RE-VERIFICATION")
print("=" * 80)

# --------------------------------------------------
# BASELINE VERIFICATION
# --------------------------------------------------

expected_rows = 180519
expected_columns = 70

print("\nCURRENT DATASET BASELINE")
print("-" * 80)
print(f"Current Dataset Rows: {df.shape[0]}")
print(f"Current Dataset Columns: {df.shape[1]}")

print("\nSTEP 17 LOCKED BASELINE VERIFICATION")
print("-" * 80)
print(f"Expected Rows: {expected_rows}")
print(f"Current Rows: {df.shape[0]}")
print(f"Row Count Difference: {df.shape[0] - expected_rows}")
print()
print(f"Expected Columns: {expected_columns}")
print(f"Current Columns: {df.shape[1]}")
print(f"Column Count Difference: {df.shape[1] - expected_columns}")

# --------------------------------------------------
# APPROVED MASTER BUSINESS COLUMN ORDER
# --------------------------------------------------

master_business_columns = [
    "Order Item Id",
    "Order Id",
    "Order Customer Id",
    "Customer Id",
    "Customer Fname",
    "Customer Lname",
    "Customer Segment",
    "Customer City",
    "Customer State",
    "Customer Country",
    "Customer Zipcode",
    "Order City",
    "Order State",
    "Order Country",
    "Order Region",
    "Order Zipcode",
    "Market",
    "Type",
    "Category Id",
    "Category Name",
    "Department Id",
    "Department Name",
    "Product Card Id",
    "Product Category Id",
    "Product Description",
    "Product Name",
    "Product Price",
    "Order Item Cardprod Id",
    "Order Item Category Id",
    "Order Item Product Price",
    "Order Item Quantity",
    "Order Item Discount",
    "Order Item Discount Rate",
    "Order Item Total",
    "Sales",
    "Benefit per order",
    "Order Item Profit Ratio",
    "Delivery Status",
    "Late delivery risk",
    "Shipping Mode",
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "order date (DateOrders)",
    "shipping date (DateOrders)",
    "Order Status",
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Order_Day_of_Week",
    "Is_Weekend_Order",
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Performance_Category",
    "Delay_Severity_Level",
    "Is_Commercial_Loss",
    "Logistics_Corridor_ID",
    "Shipping_Lane_ID"
]

# --------------------------------------------------
# APPROVED ML ANALYTICS COLUMN ORDER
# --------------------------------------------------

ml_analytics_columns = [
    "Order Item Id",
    "Delivery_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Days for shipping (real)_scaled",
    "Days for shipment (scheduled)_scaled",
    "Benefit per order_scaled",
    "Order Item Discount_scaled",
    "Order Item Discount Rate_scaled",
    "Order Item Product Price_scaled",
    "Order Item Profit Ratio_scaled",
    "Order Item Quantity_scaled",
    "Sales_scaled",
    "Order Item Total_scaled",
    "Shipping Mode",
    "Logistics_Corridor_ID"
]

# --------------------------------------------------
# MASTER BUSINESS ORDER VERIFICATION
# --------------------------------------------------

print("\nMASTER BUSINESS DATA COLUMN ORDER VERIFICATION")
print("-" * 80)

master_missing = [col for col in master_business_columns if col not in df.columns]
master_duplicates = len(master_business_columns) - len(set(master_business_columns))

master_status = (
    "PASS"
    if len(master_business_columns) == 59
    and len(master_missing) == 0
    and master_duplicates == 0
    else "REVIEW REQUIRED"
)

master_summary = pd.DataFrame({
    "Metric": [
        "Expected Master Business Columns",
        "Professional Master Order Columns",
        "Missing Master Columns in Dataset",
        "Duplicate Columns in Master Order",
        "Master Business Column Order Status"
    ],
    "Value": [
        59,
        len(master_business_columns),
        len(master_missing),
        master_duplicates,
        master_status
    ]
})

display(master_summary)

# --------------------------------------------------
# ML ANALYTICS ORDER VERIFICATION
# --------------------------------------------------

print("\nML ANALYTICS READY COLUMN ORDER VERIFICATION")
print("-" * 80)

ml_missing = [col for col in ml_analytics_columns if col not in df.columns]
ml_duplicates = len(ml_analytics_columns) - len(set(ml_analytics_columns))

ml_status = (
    "PASS"
    if len(ml_analytics_columns) == 16
    and len(ml_missing) == 0
    and ml_duplicates == 0
    else "REVIEW REQUIRED"
)

ml_summary = pd.DataFrame({
    "Metric": [
        "Expected ML Analytics Columns",
        "Professional ML Order Columns",
        "Missing ML Columns in Dataset",
        "Duplicate Columns in ML Order",
        "ML Analytics Ready Column Order Status"
    ],
    "Value": [
        16,
        len(ml_analytics_columns),
        len(ml_missing),
        ml_duplicates,
        ml_status
    ]
})

display(ml_summary)

# --------------------------------------------------
# COLUMN AVAILABILITY DETAIL
# --------------------------------------------------

print("\nCOLUMN ORDERING AVAILABILITY DETAIL")
print("-" * 80)

if len(master_missing) == 0:
    print("Master Business Missing Columns: 0")
else:
    print("Master Business Missing Columns:")
    print(master_missing)

if len(ml_missing) == 0:
    print("ML Analytics Missing Columns: 0")
else:
    print("ML Analytics Missing Columns:")
    print(ml_missing)

# --------------------------------------------------
# RELATIONAL KEY VERIFICATION
# --------------------------------------------------

print("\nRELATIONAL KEY ORDERING VERIFICATION")
print("-" * 80)

relational_key = "Order Item Id"

relational_key_summary = pd.DataFrame({
    "Verification Check": [
        "Primary Relational Key",
        "Present in Master Business Order",
        "Present in ML Analytics Order"
    ],
    "Result": [
        relational_key,
        "YES" if relational_key in master_business_columns else "NO",
        "YES" if relational_key in ml_analytics_columns else "NO"
    ]
})

display(relational_key_summary)

# --------------------------------------------------
# FINAL STATUS
# --------------------------------------------------

overall_status = (
    "PASS"
    if master_status == "PASS"
    and ml_status == "PASS"
    else "REVIEW REQUIRED"
)

print("\nFINAL PROFESSIONAL COLUMN ORDERING STATUS")
print("-" * 80)
print(f"Master Business Data Column Order Status: {master_status}")
print(f"ML Analytics Ready Column Order Status: {ml_status}")
print(f"Overall Professional Column Ordering Status: {overall_status}")

print("\nSTATUS")
print("-" * 80)

if overall_status == "PASS":
    print("STEP 18.3A professional column ordering correction completed successfully.")
    print("The approved 59-column Master Business Data order is complete.")
    print("The approved 16-column ML Analytics Ready order is complete.")
    print("No approved columns are missing from either ordering architecture.")
    print("No duplicate columns exist in either ordering architecture.")
    print("Order Item Id remains present as the common relational key.")
    print("No dataset values were modified.")
    print("No rows were removed.")
    print("No columns were removed.")
    print("No Excel workbook sheets were created in this step.")
    print("Dataset is ready for controlled workbook sheet construction.")
else:
    print("Professional column ordering still requires controlled review.")
    print("No dataset modifications were performed.")

STEP 18.3A — PROFESSIONAL COLUMN ORDERING CORRECTION & RE-VERIFICATION

CURRENT DATASET BASELINE
--------------------------------------------------------------------------------
Current Dataset Rows: 180519
Current Dataset Columns: 70

STEP 17 LOCKED BASELINE VERIFICATION
--------------------------------------------------------------------------------
Expected Rows: 180519
Current Rows: 180519
Row Count Difference: 0

Expected Columns: 70
Current Columns: 70
Column Count Difference: 0

MASTER BUSINESS DATA COLUMN ORDER VERIFICATION
--------------------------------------------------------------------------------


,Metric,Value
0,Expected Master Business Columns,59
1,Professional Master Order Columns,59
2,Missing Master Columns in Dataset,5
3,Duplicate Columns in Master Order,0
4,Master Business Column Order Status,REVIEW REQUIRED



ML ANALYTICS READY COLUMN ORDER VERIFICATION
--------------------------------------------------------------------------------


,Metric,Value
0,Expected ML Analytics Columns,16
1,Professional ML Order Columns,16
2,Missing ML Columns in Dataset,0
3,Duplicate Columns in ML Order,0
4,ML Analytics Ready Column Order Status,PASS



COLUMN ORDERING AVAILABILITY DETAIL
--------------------------------------------------------------------------------
Master Business Missing Columns:
['Order Customer Id', 'Product Category Id', 'Product Price', 'Order Item Cardprod Id', 'Order Item Category Id']
ML Analytics Missing Columns: 0

RELATIONAL KEY ORDERING VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Primary Relational Key,Order Item Id
1,Present in Master Business Order,YES
2,Present in ML Analytics Order,YES



FINAL PROFESSIONAL COLUMN ORDERING STATUS
--------------------------------------------------------------------------------
Master Business Data Column Order Status: REVIEW REQUIRED
ML Analytics Ready Column Order Status: PASS
Overall Professional Column Ordering Status: REVIEW REQUIRED

STATUS
--------------------------------------------------------------------------------
Professional column ordering still requires controlled review.
No dataset modifications were performed.


# STEP 18.3B — ACTUAL MASTER BUSINESS COLUMN ORDER CORRECTION

This step corrects the Master Business Data professional column ordering using only actual columns available in the locked 70-column dataset.

The previous STEP 18.3A review confirmed that five planned column names do not exist in the actual dataset.

Objectives:
- Use only actual dataset column names.
- Preserve the approved 59-column Master Business architecture.
- Exclude the 11 approved scaled columns from the Master Business sheet.
- Retain Order Item Id as the common relational key.
- Establish a professional logical column order without modifying dataset values.

No dataset values will be modified.
No rows will be removed.
No columns will be removed from the locked dataset.
No Excel workbook sheets will be created in this step.

In [38]:
import pandas as pd

print("STEP 18.3B — ACTUAL MASTER BUSINESS COLUMN ORDER CORRECTION")
print("=" * 80)

# --------------------------------------------------
# LOCKED DATASET BASELINE
# --------------------------------------------------

expected_rows = 180519
expected_columns = 70
expected_master_columns = 59

print("\nCURRENT DATASET BASELINE")
print("-" * 80)
print(f"Current Dataset Rows: {df.shape[0]}")
print(f"Current Dataset Columns: {df.shape[1]}")

# --------------------------------------------------
# APPROVED NON-MASTER SCALED COLUMNS
# --------------------------------------------------

scaled_columns_outside_master = [
    "Days for shipping (real)_scaled",
    "Days for shipment (scheduled)_scaled",
    "Benefit per order_scaled",
    "Order Item Discount_scaled",
    "Order Item Discount Rate_scaled",
    "Order Item Product Price_scaled",
    "Order Item Profit Ratio_scaled",
    "Order Item Quantity_scaled",
    "Sales_scaled",
    "Order Item Total_scaled",
    "Order Zipcode_scaled"
]

print("\nAPPROVED SCALED COLUMN EXCLUSIONS FROM MASTER BUSINESS DATA")
print("-" * 80)

scaled_exclusion_check = pd.DataFrame({
    "Scaled Column": scaled_columns_outside_master,
    "Available in Dataset": [
        "YES" if col in df.columns else "NO"
        for col in scaled_columns_outside_master
    ]
})

display(scaled_exclusion_check)

# --------------------------------------------------
# ACTUAL MASTER BUSINESS COLUMN IDENTIFICATION
# --------------------------------------------------

actual_master_columns = [
    col for col in df.columns
    if col not in scaled_columns_outside_master
]

print("\nACTUAL MASTER BUSINESS COLUMN IDENTIFICATION")
print("-" * 80)
print(f"Expected Master Business Columns: {expected_master_columns}")
print(f"Actual Master Business Columns Identified: {len(actual_master_columns)}")

# --------------------------------------------------
# PROFESSIONAL COLUMN ORDER GROUPS
# --------------------------------------------------

preferred_master_order = [
    # Primary identifiers and order references
    "Order Item Id",
    "Order Id",
    "Customer Id",

    # Customer information
    "Customer Fname",
    "Customer Lname",
    "Customer Segment",
    "Customer City",
    "Customer State",
    "Customer Country",
    "Customer Zipcode",
    "Customer Email",

    # Geographic and market information
    "Order City",
    "Order State",
    "Order Country",
    "Order Region",
    "Order Zipcode",
    "Market",

    # Product and category information
    "Product Card Id",
    "Product Category Id",
    "Product Name",
    "Product Description",
    "Category Id",
    "Category Name",
    "Department Id",
    "Department Name",

    # Order item and commercial information
    "Order Item Product Price",
    "Order Item Quantity",
    "Order Item Discount",
    "Order Item Discount Rate",
    "Order Item Total",
    "Sales",
    "Benefit per order",
    "Order Item Profit Ratio",

    # Operational and shipping information
    "Type",
    "Delivery Status",
    "Late delivery risk",
    "Shipping Mode",
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Order Status",

    # Date information
    "order date (DateOrders)",
    "shipping date (DateOrders)",

    # Feature engineered delivery and performance information
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Performance_Category",
    "Delay_Severity_Level",

    # Date-derived engineered features
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Order_Day_of_Week",
    "Is_Weekend_Order",

    # Commercial and logistics engineered features
    "Is_Commercial_Loss",
    "Logistics_Corridor_ID",
    "Shipping_Lane_ID",
    "Is_Cross_Border"
]

# Keep only actual dataset columns from preferred order
professional_master_order = [
    col for col in preferred_master_order
    if col in actual_master_columns
]

# Add any remaining actual master columns not already included
remaining_master_columns = [
    col for col in actual_master_columns
    if col not in professional_master_order
]

professional_master_order.extend(remaining_master_columns)

# --------------------------------------------------
# FINAL MASTER ORDER VALIDATION
# --------------------------------------------------

missing_from_order = [
    col for col in actual_master_columns
    if col not in professional_master_order
]

unexpected_in_order = [
    col for col in professional_master_order
    if col not in actual_master_columns
]

duplicate_order_columns = (
    len(professional_master_order)
    - len(set(professional_master_order))
)

master_order_status = (
    "PASS"
    if len(actual_master_columns) == expected_master_columns
    and len(professional_master_order) == expected_master_columns
    and len(missing_from_order) == 0
    and len(unexpected_in_order) == 0
    and duplicate_order_columns == 0
    else "REVIEW REQUIRED"
)

print("\nMASTER BUSINESS PROFESSIONAL COLUMN ORDER VERIFICATION")
print("-" * 80)

master_order_summary = pd.DataFrame({
    "Metric": [
        "Expected Master Business Columns",
        "Actual Master Business Columns",
        "Professional Master Order Columns",
        "Actual Columns Missing From Order",
        "Unexpected Columns in Order",
        "Duplicate Columns in Order",
        "Master Business Column Order Status"
    ],
    "Value": [
        expected_master_columns,
        len(actual_master_columns),
        len(professional_master_order),
        len(missing_from_order),
        len(unexpected_in_order),
        duplicate_order_columns,
        master_order_status
    ]
})

display(master_order_summary)

# --------------------------------------------------
# COLUMN ORDER REGISTER
# --------------------------------------------------

print("\nFINAL PROFESSIONAL MASTER BUSINESS COLUMN ORDER")
print("-" * 80)

master_order_register = pd.DataFrame({
    "Professional Order": range(1, len(professional_master_order) + 1),
    "Column Name": professional_master_order
})

display(master_order_register)

# --------------------------------------------------
# RELATIONAL KEY VERIFICATION
# --------------------------------------------------

print("\nRELATIONAL KEY VERIFICATION")
print("-" * 80)

relational_key = "Order Item Id"

relational_key_summary = pd.DataFrame({
    "Verification Check": [
        "Primary Relational Key",
        "Available in Dataset",
        "Present in Professional Master Order"
    ],
    "Result": [
        relational_key,
        "YES" if relational_key in df.columns else "NO",
        "YES" if relational_key in professional_master_order else "NO"
    ]
})

display(relational_key_summary)

# --------------------------------------------------
# FINAL STATUS
# --------------------------------------------------

print("\nFINAL MASTER BUSINESS COLUMN ORDERING STATUS")
print("-" * 80)
print(f"Master Business Data Column Order Status: {master_order_status}")

print("\nSTATUS")
print("-" * 80)

if master_order_status == "PASS":
    print("STEP 18.3B Master Business column ordering correction completed successfully.")
    print("All 59 actual Master Business columns are included exactly once.")
    print("Only actual dataset columns were used.")
    print("All 11 approved scaled columns remain excluded from Master Business Data.")
    print("Order Item Id remains preserved as the primary relational key.")
    print("No dataset values were modified.")
    print("No rows were removed.")
    print("No dataset columns were removed.")
    print("No Excel workbook sheets were created in this step.")
else:
    print("Master Business column ordering requires additional controlled review.")
    print("No dataset modifications were performed.")

STEP 18.3B — ACTUAL MASTER BUSINESS COLUMN ORDER CORRECTION

CURRENT DATASET BASELINE
--------------------------------------------------------------------------------
Current Dataset Rows: 180519
Current Dataset Columns: 70

APPROVED SCALED COLUMN EXCLUSIONS FROM MASTER BUSINESS DATA
--------------------------------------------------------------------------------


,Scaled Column,Available in Dataset
0,Days for shipping (real)_scaled,YES
1,Days for shipment (scheduled)_scaled,YES
2,Benefit per order_scaled,YES
3,Order Item Discount_scaled,YES
4,Order Item Discount Rate_scaled,YES
5,Order Item Product Price_scaled,YES
6,Order Item Profit Ratio_scaled,YES
7,Order Item Quantity_scaled,YES
8,Sales_scaled,YES
9,Order Item Total_scaled,YES



ACTUAL MASTER BUSINESS COLUMN IDENTIFICATION
--------------------------------------------------------------------------------
Expected Master Business Columns: 59
Actual Master Business Columns Identified: 59

MASTER BUSINESS PROFESSIONAL COLUMN ORDER VERIFICATION
--------------------------------------------------------------------------------


,Metric,Value
0,Expected Master Business Columns,59
1,Actual Master Business Columns,59
2,Professional Master Order Columns,59
3,Actual Columns Missing From Order,0
4,Unexpected Columns in Order,0
5,Duplicate Columns in Order,0
6,Master Business Column Order Status,PASS



FINAL PROFESSIONAL MASTER BUSINESS COLUMN ORDER
--------------------------------------------------------------------------------


,Professional Order,Column Name
0,1,Order Item Id
1,2,Order Id
2,3,Customer Id
3,4,Customer Fname
4,5,Customer Lname
5,6,Customer Segment
6,7,Customer City
7,8,Customer State
8,9,Customer Country
9,10,Customer Zipcode



RELATIONAL KEY VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Primary Relational Key,Order Item Id
1,Available in Dataset,YES
2,Present in Professional Master Order,YES



FINAL MASTER BUSINESS COLUMN ORDERING STATUS
--------------------------------------------------------------------------------
Master Business Data Column Order Status: PASS

STATUS
--------------------------------------------------------------------------------
STEP 18.3B Master Business column ordering correction completed successfully.
All 59 actual Master Business columns are included exactly once.
Only actual dataset columns were used.
All 11 approved scaled columns remain excluded from Master Business Data.
Order Item Id remains preserved as the primary relational key.
No dataset values were modified.
No rows were removed.
No dataset columns were removed.
No Excel workbook sheets were created in this step.


# STEP 18.3C — ML ANALYTICS READY PROFESSIONAL COLUMN ORDERING & FINAL VERIFICATION

This step defines and verifies the professional column order for the Logistic_ML_Analytics_Ready workbook sheet.

The verification confirms that all 16 approved ML Analytics Ready columns are included exactly once and are available in the locked Feature Engineering dataset.

Order Item Id remains preserved as the common relational key between Logistic_Master_Business_Data and Logistic_ML_Analytics_Ready.

No dataset values, rows, or source columns will be modified in this step.
No Excel workbook sheets will be created in this step.

In [39]:
import pandas as pd

print("STEP 18.3C — ML ANALYTICS READY PROFESSIONAL COLUMN ORDERING & FINAL VERIFICATION")
print("=" * 80)

print("\nCURRENT DATASET BASELINE")
print("-" * 80)
print(f"Current Dataset Rows: {df.shape[0]}")
print(f"Current Dataset Columns: {df.shape[1]}")

ml_analytics_order = [
    "Order Item Id",
    "Days for shipping (real)_scaled",
    "Days for shipment (scheduled)_scaled",
    "Benefit per order_scaled",
    "Order Item Discount_scaled",
    "Order Item Discount Rate_scaled",
    "Order Item Product Price_scaled",
    "Order Item Profit Ratio_scaled",
    "Order Item Quantity_scaled",
    "Sales_scaled",
    "Order Item Total_scaled",
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Late delivery risk"
]

print("\nAPPROVED ML ANALYTICS READY COLUMN IDENTIFICATION")
print("-" * 80)

expected_ml_columns = 16
actual_ml_columns = len(ml_analytics_order)

print(f"Expected ML Analytics Ready Columns: {expected_ml_columns}")
print(f"Professional ML Analytics Order Columns: {actual_ml_columns}")

missing_ml_columns = [
    column for column in ml_analytics_order
    if column not in df.columns
]

unexpected_ml_columns = [
    column for column in ml_analytics_order
    if column not in df.columns
]

duplicate_ml_columns = pd.Series(ml_analytics_order).duplicated().sum()

ml_order_verification = pd.DataFrame({
    "Metric": [
        "Expected ML Analytics Columns",
        "Professional ML Analytics Order Columns",
        "Actual Columns Missing From Order",
        "Unexpected Columns in Order",
        "Duplicate Columns in Order",
        "ML Analytics Ready Column Order Status"
    ],
    "Value": [
        expected_ml_columns,
        actual_ml_columns,
        len(missing_ml_columns),
        len(unexpected_ml_columns),
        duplicate_ml_columns,
        "PASS" if (
            len(missing_ml_columns) == 0
            and len(unexpected_ml_columns) == 0
            and duplicate_ml_columns == 0
            and actual_ml_columns == expected_ml_columns
        ) else "REVIEW REQUIRED"
    ]
})

print("\nML ANALYTICS READY PROFESSIONAL COLUMN ORDER VERIFICATION")
print("-" * 80)
display(ml_order_verification)

ml_order_table = pd.DataFrame({
    "Professional Order": range(1, len(ml_analytics_order) + 1),
    "Column Name": ml_analytics_order
})

print("\nFINAL PROFESSIONAL ML ANALYTICS READY COLUMN ORDER")
print("-" * 80)
display(ml_order_table)

relational_key_verification = pd.DataFrame({
    "Verification Check": [
        "Primary Relational Key",
        "Available in Dataset",
        "Present in Professional ML Analytics Order"
    ],
    "Result": [
        "Order Item Id",
        "YES" if "Order Item Id" in df.columns else "NO",
        "YES" if "Order Item Id" in ml_analytics_order else "NO"
    ]
})

print("\nRELATIONAL KEY VERIFICATION")
print("-" * 80)
display(relational_key_verification)

final_status = (
    len(missing_ml_columns) == 0
    and len(unexpected_ml_columns) == 0
    and duplicate_ml_columns == 0
    and actual_ml_columns == expected_ml_columns
    and "Order Item Id" in df.columns
)

print("\nFINAL ML ANALYTICS READY COLUMN ORDERING STATUS")
print("-" * 80)
print(f"ML Analytics Ready Column Order Status: {'PASS' if final_status else 'REVIEW REQUIRED'}")

print("\nSTATUS")
print("-" * 80)

if final_status:
    print("STEP 18.3C ML Analytics Ready professional column ordering verification completed successfully.")
    print("All 16 approved ML Analytics Ready columns are included exactly once.")
    print("Only actual dataset columns were used.")
    print("Order Item Id remains preserved as the common relational key.")
    print("No dataset values were modified.")
    print("No rows were removed.")
    print("No dataset columns were removed.")
    print("No Excel workbook sheets were created in this step.")
else:
    print("ML Analytics Ready column ordering requires controlled review.")

STEP 18.3C — ML ANALYTICS READY PROFESSIONAL COLUMN ORDERING & FINAL VERIFICATION

CURRENT DATASET BASELINE
--------------------------------------------------------------------------------
Current Dataset Rows: 180519
Current Dataset Columns: 70

APPROVED ML ANALYTICS READY COLUMN IDENTIFICATION
--------------------------------------------------------------------------------
Expected ML Analytics Ready Columns: 16
Professional ML Analytics Order Columns: 16

ML ANALYTICS READY PROFESSIONAL COLUMN ORDER VERIFICATION
--------------------------------------------------------------------------------


,Metric,Value
0,Expected ML Analytics Columns,16
1,Professional ML Analytics Order Columns,16
2,Actual Columns Missing From Order,0
3,Unexpected Columns in Order,0
4,Duplicate Columns in Order,0
5,ML Analytics Ready Column Order Status,PASS



FINAL PROFESSIONAL ML ANALYTICS READY COLUMN ORDER
--------------------------------------------------------------------------------


,Professional Order,Column Name
0,1,Order Item Id
1,2,Days for shipping (real)_scaled
2,3,Days for shipment (scheduled)_scaled
3,4,Benefit per order_scaled
4,5,Order Item Discount_scaled
5,6,Order Item Discount Rate_scaled
6,7,Order Item Product Price_scaled
7,8,Order Item Profit Ratio_scaled
8,9,Order Item Quantity_scaled
9,10,Sales_scaled



RELATIONAL KEY VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Primary Relational Key,Order Item Id
1,Available in Dataset,YES
2,Present in Professional ML Analytics Order,YES



FINAL ML ANALYTICS READY COLUMN ORDERING STATUS
--------------------------------------------------------------------------------
ML Analytics Ready Column Order Status: PASS

STATUS
--------------------------------------------------------------------------------
STEP 18.3C ML Analytics Ready professional column ordering verification completed successfully.
All 16 approved ML Analytics Ready columns are included exactly once.
Only actual dataset columns were used.
Order Item Id remains preserved as the common relational key.
No dataset values were modified.
No rows were removed.
No dataset columns were removed.
No Excel workbook sheets were created in this step.


# STEP 18.4 — EXCEL WORKBOOK SHEET CREATION & CONTROLLED DATA ALLOCATION

This step creates controlled dataset copies for the approved Excel workbook architecture.

Approved workbook sheets:

1. Logistic_Master_Business_Data
   - 59 professionally ordered business columns
   - Order Item Id preserved as the primary relational key

2. Logistic_ML_Analytics_Ready
   - 16 professionally ordered analytics and machine learning columns
   - Order Item Id preserved as the common relational key

Control requirements:

- STEP 17 locked dataset remains unchanged.
- No rows will be removed.
- No dataset values will be modified.
- No source columns will be removed from the original dataset.
- Controlled sheet copies will be created using the approved column orders.
- Both sheet datasets must preserve all 180519 rows.
- Column allocation must exactly match the approved STEP 18.3B and STEP 18.3C structures.
- Order Item Id must remain available in both sheet datasets as the common relational key.
- Excel workbook export will not be performed in this verification step.

In [40]:
import pandas as pd

print("STEP 18.4 — EXCEL WORKBOOK SHEET CREATION & CONTROLLED DATA ALLOCATION")
print("=" * 80)

locked_rows = 180519
locked_columns = 70

print("\nCURRENT DATASET BASELINE")
print("-" * 80)
print(f"Current Dataset Rows: {df.shape[0]}")
print(f"Current Dataset Columns: {df.shape[1]}")

if df.shape[0] != locked_rows:
    raise ValueError(
        f"Dataset row baseline mismatch. Expected {locked_rows}, found {df.shape[0]}."
    )

if df.shape[1] != locked_columns:
    raise ValueError(
        f"Dataset column baseline mismatch. Expected {locked_columns}, found {df.shape[1]}."
    )

print("\nSTEP 17 LOCKED BASELINE STATUS: PASS")

master_business_columns = [
    "Order Item Id",
    "Order Id",
    "Customer Id",
    "Customer Fname",
    "Customer Lname",
    "Customer Segment",
    "Customer City",
    "Customer State",
    "Customer Country",
    "Customer Zipcode",
    "Customer Email",
    "Order City",
    "Order State",
    "Order Country",
    "Order Region",
    "Order Zipcode",
    "Market",
    "Product Card Id",
    "Product Name",
    "Product Description",
    "Category Id",
    "Category Name",
    "Department Id",
    "Department Name",
    "Order Item Product Price",
    "Order Item Quantity",
    "Order Item Discount",
    "Order Item Discount Rate",
    "Order Item Total",
    "Sales",
    "Benefit per order",
    "Order Item Profit Ratio",
    "Type",
    "Delivery Status",
    "Late delivery risk",
    "Shipping Mode",
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Order Status",
    "order date (DateOrders)",
    "shipping date (DateOrders)",
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Performance_Category",
    "Delay_Severity_Level",
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Order_Day_of_Week",
    "Is_Weekend_Order",
    "Is_Commercial_Loss",
    "Logistics_Corridor_ID",
    "Shipping_Lane_ID",
    "Is_Cross_Border",
    "Customer Street",
    "Latitude",
    "Longitude"
]

ml_analytics_columns = [
    "Order Item Id",
    "Days for shipping (real)_scaled",
    "Days for shipment (scheduled)_scaled",
    "Benefit per order_scaled",
    "Order Item Discount_scaled",
    "Order Item Discount Rate_scaled",
    "Order Item Product Price_scaled",
    "Order Item Profit Ratio_scaled",
    "Order Item Quantity_scaled",
    "Sales_scaled",
    "Order Item Total_scaled",
    "Delivery_Time_Hours",
    "Promised_Time_Hours",
    "Delay_Hours",
    "Delay_Flag",
    "Late delivery risk"
]

print("\nAPPROVED SHEET ARCHITECTURE")
print("-" * 80)

architecture_summary = pd.DataFrame({
    "Workbook Sheet": [
        "Logistic_Master_Business_Data",
        "Logistic_ML_Analytics_Ready"
    ],
    "Expected Columns": [
        len(master_business_columns),
        len(ml_analytics_columns)
    ],
    "Common Relational Key": [
        "Order Item Id",
        "Order Item Id"
    ]
})

display(architecture_summary)

missing_master_columns = [
    column for column in master_business_columns
    if column not in df.columns
]

missing_ml_columns = [
    column for column in ml_analytics_columns
    if column not in df.columns
]

if missing_master_columns:
    raise ValueError(
        f"Missing Master Business columns: {missing_master_columns}"
    )

if missing_ml_columns:
    raise ValueError(
        f"Missing ML Analytics columns: {missing_ml_columns}"
    )

print("\nCOLUMN AVAILABILITY VERIFICATION")
print("-" * 80)
print(f"Master Business Columns Expected: {len(master_business_columns)}")
print(f"Master Business Columns Available: {len(master_business_columns) - len(missing_master_columns)}")
print(f"Master Business Columns Missing: {len(missing_master_columns)}")

print(f"\nML Analytics Columns Expected: {len(ml_analytics_columns)}")
print(f"ML Analytics Columns Available: {len(ml_analytics_columns) - len(missing_ml_columns)}")
print(f"ML Analytics Columns Missing: {len(missing_ml_columns)}")

master_business_df = df.loc[:, master_business_columns].copy()

ml_analytics_df = df.loc[:, ml_analytics_columns].copy()

print("\nCONTROLLED SHEET DATA CREATION")
print("-" * 80)
print("Logistic_Master_Business_Data copy created.")
print("Logistic_ML_Analytics_Ready copy created.")

print("\nSHEET STRUCTURAL VERIFICATION")
print("-" * 80)

sheet_verification = pd.DataFrame({
    "Workbook Sheet": [
        "Logistic_Master_Business_Data",
        "Logistic_ML_Analytics_Ready"
    ],
    "Expected Rows": [
        locked_rows,
        locked_rows
    ],
    "Actual Rows": [
        master_business_df.shape[0],
        ml_analytics_df.shape[0]
    ],
    "Expected Columns": [
        59,
        16
    ],
    "Actual Columns": [
        master_business_df.shape[1],
        ml_analytics_df.shape[1]
    ]
})

sheet_verification["Row Count Difference"] = (
    sheet_verification["Actual Rows"]
    - sheet_verification["Expected Rows"]
)

sheet_verification["Column Count Difference"] = (
    sheet_verification["Actual Columns"]
    - sheet_verification["Expected Columns"]
)

display(sheet_verification)

if master_business_df.shape[0] != locked_rows:
    raise ValueError("Master Business Data row count verification failed.")

if ml_analytics_df.shape[0] != locked_rows:
    raise ValueError("ML Analytics Ready row count verification failed.")

if master_business_df.shape[1] != 59:
    raise ValueError("Master Business Data column count verification failed.")

if ml_analytics_df.shape[1] != 16:
    raise ValueError("ML Analytics Ready column count verification failed.")

print("\nRELATIONAL KEY VERIFICATION")
print("-" * 80)

relational_key_verification = pd.DataFrame({
    "Verification Check": [
        "Primary Relational Key",
        "Key Present in Master Business Data",
        "Key Present in ML Analytics Ready Data",
        "Master Business Key Missing Values",
        "ML Analytics Key Missing Values",
        "Master Business Duplicate Key Values",
        "ML Analytics Duplicate Key Values"
    ],
    "Result": [
        "Order Item Id",
        "YES" if "Order Item Id" in master_business_df.columns else "NO",
        "YES" if "Order Item Id" in ml_analytics_df.columns else "NO",
        master_business_df["Order Item Id"].isna().sum(),
        ml_analytics_df["Order Item Id"].isna().sum(),
        master_business_df["Order Item Id"].duplicated().sum(),
        ml_analytics_df["Order Item Id"].duplicated().sum()
    ]
})

display(relational_key_verification)

if "Order Item Id" not in master_business_df.columns:
    raise ValueError("Order Item Id missing from Master Business Data.")

if "Order Item Id" not in ml_analytics_df.columns:
    raise ValueError("Order Item Id missing from ML Analytics Ready Data.")

if master_business_df["Order Item Id"].isna().sum() != 0:
    raise ValueError("Missing relational key values found in Master Business Data.")

if ml_analytics_df["Order Item Id"].isna().sum() != 0:
    raise ValueError("Missing relational key values found in ML Analytics Ready Data.")

if master_business_df["Order Item Id"].duplicated().sum() != 0:
    raise ValueError("Duplicate relational key values found in Master Business Data.")

if ml_analytics_df["Order Item Id"].duplicated().sum() != 0:
    raise ValueError("Duplicate relational key values found in ML Analytics Ready Data.")

print("\nORIGINAL DATASET PRESERVATION VERIFICATION")
print("-" * 80)

original_dataset_check = pd.DataFrame({
    "Verification Check": [
        "Original Dataset Rows",
        "Expected Locked Rows",
        "Original Dataset Columns",
        "Expected Locked Columns",
        "Original Dataset Row Structure Preserved",
        "Original Dataset Column Structure Preserved"
    ],
    "Result": [
        df.shape[0],
        locked_rows,
        df.shape[1],
        locked_columns,
        "PASS" if df.shape[0] == locked_rows else "FAIL",
        "PASS" if df.shape[1] == locked_columns else "FAIL"
    ]
})

display(original_dataset_check)

print("\nSTEP 18.4 CONTROLLED DATA ALLOCATION STATUS")
print("-" * 80)
print("Overall Status: PASS")

print("\nSTATUS")
print("-" * 80)
print("STEP 18.4 controlled workbook sheet data allocation completed successfully.")
print("Logistic_Master_Business_Data dataset copy verified at 180519 rows and 59 columns.")
print("Logistic_ML_Analytics_Ready dataset copy verified at 180519 rows and 16 columns.")
print("Order Item Id is preserved as the common relational key.")
print("All approved professional column orders were applied.")
print("The original 70-column STEP 17 locked dataset remains unchanged.")
print("No rows were removed.")
print("No dataset columns were removed from the original dataset.")
print("No data values were modified.")
print("No Excel workbook export was performed in this step.")
print("Controlled datasets are ready for workbook creation and export.")

STEP 18.4 — EXCEL WORKBOOK SHEET CREATION & CONTROLLED DATA ALLOCATION

CURRENT DATASET BASELINE
--------------------------------------------------------------------------------
Current Dataset Rows: 180519
Current Dataset Columns: 70

STEP 17 LOCKED BASELINE STATUS: PASS

APPROVED SHEET ARCHITECTURE
--------------------------------------------------------------------------------


,Workbook Sheet,Expected Columns,Common Relational Key
0,Logistic_Master_Business_Data,59,Order Item Id
1,Logistic_ML_Analytics_Ready,16,Order Item Id



COLUMN AVAILABILITY VERIFICATION
--------------------------------------------------------------------------------
Master Business Columns Expected: 59
Master Business Columns Available: 59
Master Business Columns Missing: 0

ML Analytics Columns Expected: 16
ML Analytics Columns Available: 16
ML Analytics Columns Missing: 0

CONTROLLED SHEET DATA CREATION
--------------------------------------------------------------------------------
Logistic_Master_Business_Data copy created.
Logistic_ML_Analytics_Ready copy created.

SHEET STRUCTURAL VERIFICATION
--------------------------------------------------------------------------------


,Workbook Sheet,Expected Rows,Actual Rows,Expected Columns,Actual Columns,Row Count Difference,Column Count Difference
0,Logistic_Master_Business_Data,180519,180519,59,59,0,0
1,Logistic_ML_Analytics_Ready,180519,180519,16,16,0,0



RELATIONAL KEY VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Primary Relational Key,Order Item Id
1,Key Present in Master Business Data,YES
2,Key Present in ML Analytics Ready Data,YES
3,Master Business Key Missing Values,0
4,ML Analytics Key Missing Values,0
5,Master Business Duplicate Key Values,0
6,ML Analytics Duplicate Key Values,0



ORIGINAL DATASET PRESERVATION VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Original Dataset Rows,180519
1,Expected Locked Rows,180519
2,Original Dataset Columns,70
3,Expected Locked Columns,70
4,Original Dataset Row Structure Preserved,PASS
5,Original Dataset Column Structure Preserved,PASS



STEP 18.4 CONTROLLED DATA ALLOCATION STATUS
--------------------------------------------------------------------------------
Overall Status: PASS

STATUS
--------------------------------------------------------------------------------
STEP 18.4 controlled workbook sheet data allocation completed successfully.
Logistic_Master_Business_Data dataset copy verified at 180519 rows and 59 columns.
Logistic_ML_Analytics_Ready dataset copy verified at 180519 rows and 16 columns.
Order Item Id is preserved as the common relational key.
All approved professional column orders were applied.
The original 70-column STEP 17 locked dataset remains unchanged.
No rows were removed.
No dataset columns were removed from the original dataset.
No data values were modified.
No Excel workbook export was performed in this step.
Controlled datasets are ready for workbook creation and export.


# STEP 18.5 — PROFESSIONAL EXCEL WORKBOOK CREATION & EXPORT

This step creates the final professional Excel workbook using the controlled datasets approved in STEP 18.4.

Workbook structure:

1. Logistic_Master_Business_Data
   - 180519 rows
   - 59 professionally ordered columns

2. Logistic_ML_Analytics_Ready
   - 180519 rows
   - 16 professionally ordered analytics and machine learning columns

Control requirements:

- The approved STEP 18.4 controlled datasets will be used.
- Order Item Id will remain preserved in both workbook sheets.
- No rows will be removed.
- No data values will be modified.
- Professional column ordering will remain unchanged.
- The original STEP 17 locked dataset will remain unchanged.
- The workbook will contain only the two approved data sheets.
- Excel export will be performed after structural verification.
- The exported workbook will require post-export verification in the next step.

In [41]:
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter
from pathlib import Path

print("STEP 18.5 — PROFESSIONAL EXCEL WORKBOOK CREATION & EXPORT")
print("=" * 80)

print("\nPRE-EXPORT CONTROLLED DATASET VERIFICATION")
print("-" * 80)

if master_business_df.shape != (180519, 59):
    raise ValueError(
        f"Master Business dataset structure mismatch: {master_business_df.shape}"
    )

if ml_analytics_df.shape != (180519, 16):
    raise ValueError(
        f"ML Analytics dataset structure mismatch: {ml_analytics_df.shape}"
    )

if "Order Item Id" not in master_business_df.columns:
    raise ValueError("Order Item Id missing from Master Business dataset.")

if "Order Item Id" not in ml_analytics_df.columns:
    raise ValueError("Order Item Id missing from ML Analytics dataset.")

print(f"Master Business Dataset: {master_business_df.shape[0]} rows × {master_business_df.shape[1]} columns")
print(f"ML Analytics Dataset: {ml_analytics_df.shape[0]} rows × {ml_analytics_df.shape[1]} columns")
print("Pre-export controlled dataset verification: PASS")

output_file = "Logistic_Data_Analyst_Professional_Workbook_Week2.xlsx"

print("\nWORKBOOK CREATION")
print("-" * 80)
print(f"Workbook File: {output_file}")

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    master_business_df.to_excel(
        writer,
        sheet_name="Logistic_Master_Business_Data",
        index=False
    )

    ml_analytics_df.to_excel(
        writer,
        sheet_name="Logistic_ML_Analytics_Ready",
        index=False
    )

print("Workbook data export completed.")

print("\nPOST-EXPORT WORKBOOK STRUCTURE FORMATTING")
print("-" * 80)

workbook = load_workbook(output_file)

for sheet_name in workbook.sheetnames:

    worksheet = workbook[sheet_name]

    worksheet.freeze_panes = "A2"
    worksheet.auto_filter.ref = worksheet.dimensions

    for column_index, column_name in enumerate(
        worksheet.iter_cols(
            min_row=1,
            max_row=1
        ),
        start=1
    ):
        column_letter = get_column_letter(column_index)
        header_value = column_name[0].value

        if header_value is not None:
            calculated_width = len(str(header_value)) + 2

            if calculated_width < 12:
                calculated_width = 12

            if calculated_width > 35:
                calculated_width = 35

            worksheet.column_dimensions[
                column_letter
            ].width = calculated_width

workbook.save(output_file)

print("Workbook formatting completed.")

print("\nWORKBOOK FILE VERIFICATION")
print("-" * 80)

output_path = Path(output_file)

if not output_path.exists():
    raise FileNotFoundError(
        "Workbook export failed. Output file was not created."
    )

file_size_mb = output_path.stat().st_size / (1024 * 1024)

print(f"Workbook File Exists: YES")
print(f"Workbook File Name: {output_file}")
print(f"Workbook File Size: {file_size_mb:.2f} MB")

print("\nEXPORTED WORKBOOK SHEET REGISTER")
print("-" * 80)

exported_workbook = load_workbook(
    output_file,
    read_only=True
)

sheet_register = pd.DataFrame({
    "Sheet Number": range(
        1,
        len(exported_workbook.sheetnames) + 1
    ),
    "Workbook Sheet": exported_workbook.sheetnames
})

display(sheet_register)

expected_sheets = [
    "Logistic_Master_Business_Data",
    "Logistic_ML_Analytics_Ready"
]

if exported_workbook.sheetnames != expected_sheets:
    raise ValueError(
        f"Workbook sheet architecture mismatch: {exported_workbook.sheetnames}"
    )

print("\nWORKBOOK ARCHITECTURE VERIFICATION")
print("-" * 80)
print(f"Expected Workbook Sheets: {len(expected_sheets)}")
print(f"Actual Workbook Sheets: {len(exported_workbook.sheetnames)}")
print("Workbook Sheet Architecture Status: PASS")

print("\nSTEP 18.5 EXPORT STATUS")
print("-" * 80)
print("Overall Status: PASS")

print("\nSTATUS")
print("-" * 80)
print("STEP 18.5 professional Excel workbook creation completed successfully.")
print("Logistic_Master_Business_Data exported successfully.")
print("Logistic_ML_Analytics_Ready exported successfully.")
print("Both approved workbook sheets were created.")
print("Professional column ordering was preserved.")
print("Order Item Id remains present as the common relational key.")
print("Freeze panes and autofilters were applied.")
print("Column widths were adjusted for professional workbook readability.")
print("The original STEP 17 locked dataset remains unchanged.")
print("No rows were removed.")
print("No data values were modified.")
print("Workbook export completed successfully.")
print("Post-export data-level verification is required in the next step.")

STEP 18.5 — PROFESSIONAL EXCEL WORKBOOK CREATION & EXPORT

PRE-EXPORT CONTROLLED DATASET VERIFICATION
--------------------------------------------------------------------------------
Master Business Dataset: 180519 rows × 59 columns
ML Analytics Dataset: 180519 rows × 16 columns
Pre-export controlled dataset verification: PASS

WORKBOOK CREATION
--------------------------------------------------------------------------------
Workbook File: Logistic_Data_Analyst_Professional_Workbook_Week2.xlsx
Workbook data export completed.

POST-EXPORT WORKBOOK STRUCTURE FORMATTING
--------------------------------------------------------------------------------
Workbook formatting completed.

WORKBOOK FILE VERIFICATION
--------------------------------------------------------------------------------
Workbook File Exists: YES
Workbook File Name: Logistic_Data_Analyst_Professional_Workbook_Week2.xlsx
Workbook File Size: 77.16 MB

EXPORTED WORKBOOK SHEET REGISTER
-----------------------------------------

,Sheet Number,Workbook Sheet
0,1,Logistic_Master_Business_Data
1,2,Logistic_ML_Analytics_Ready



WORKBOOK ARCHITECTURE VERIFICATION
--------------------------------------------------------------------------------
Expected Workbook Sheets: 2
Actual Workbook Sheets: 2
Workbook Sheet Architecture Status: PASS

STEP 18.5 EXPORT STATUS
--------------------------------------------------------------------------------
Overall Status: PASS

STATUS
--------------------------------------------------------------------------------
STEP 18.5 professional Excel workbook creation completed successfully.
Logistic_Master_Business_Data exported successfully.
Logistic_ML_Analytics_Ready exported successfully.
Both approved workbook sheets were created.
Professional column ordering was preserved.
Order Item Id remains present as the common relational key.
Freeze panes and autofilters were applied.
Column widths were adjusted for professional workbook readability.
The original STEP 17 locked dataset remains unchanged.
No rows were removed.
No data values were modified.
Workbook export completed succes

# STEP 18.6 — POST-EXPORT EXCEL WORKBOOK DATA INTEGRITY VERIFICATION

This step independently reopens the exported Excel workbook and verifies the final workbook structure after export.

Verification scope:

- Confirm workbook file availability.
- Confirm the exact two approved workbook sheets.
- Verify row and column counts in each exported sheet.
- Verify professional column ordering.
- Verify Order Item Id as the common relational key.
- Verify missing relational key values.
- Verify duplicate relational key values.
- Verify exported sheet column structures against the approved STEP 18.3B and STEP 18.3C definitions.
- Verify the original STEP 17 locked dataset remains unchanged.

No modifications will be performed on the Excel workbook or the original dataset during this verification step.

In [42]:
from openpyxl import load_workbook
from pathlib import Path

print("STEP 18.6 — POST-EXPORT EXCEL WORKBOOK DATA INTEGRITY VERIFICATION")
print("=" * 80)

output_file = "Logistic_Data_Analyst_Professional_Workbook_Week2.xlsx"

expected_sheets = [
    "Logistic_Master_Business_Data",
    "Logistic_ML_Analytics_Ready"
]

print("\nWORKBOOK FILE AVAILABILITY VERIFICATION")
print("-" * 80)

output_path = Path(output_file)

if not output_path.exists():
    raise FileNotFoundError(
        f"Exported workbook not found: {output_file}"
    )

print(f"Workbook File: {output_file}")
print("Workbook File Available: YES")

print("\nEXACT WORKBOOK SHEET ARCHITECTURE VERIFICATION")
print("-" * 80)

workbook_check = load_workbook(
    output_file,
    read_only=True,
    data_only=False
)

actual_sheets = workbook_check.sheetnames

sheet_architecture_verification = pd.DataFrame({
    "Verification Check": [
        "Expected Workbook Sheets",
        "Actual Workbook Sheets",
        "Expected Sheet Count",
        "Actual Sheet Count",
        "Exact Sheet Architecture Match"
    ],
    "Result": [
        ", ".join(expected_sheets),
        ", ".join(actual_sheets),
        len(expected_sheets),
        len(actual_sheets),
        "PASS" if actual_sheets == expected_sheets else "FAIL"
    ]
})

display(sheet_architecture_verification)

if actual_sheets != expected_sheets:
    raise ValueError(
        f"Workbook sheet architecture mismatch. Found: {actual_sheets}"
    )

print("\nPOST-EXPORT SHEET STRUCTURE VERIFICATION")
print("-" * 80)

master_export_df = pd.read_excel(
    output_file,
    sheet_name="Logistic_Master_Business_Data"
)

ml_export_df = pd.read_excel(
    output_file,
    sheet_name="Logistic_ML_Analytics_Ready"
)

sheet_structure_verification = pd.DataFrame({
    "Workbook Sheet": [
        "Logistic_Master_Business_Data",
        "Logistic_ML_Analytics_Ready"
    ],
    "Expected Rows": [
        180519,
        180519
    ],
    "Actual Rows": [
        master_export_df.shape[0],
        ml_export_df.shape[0]
    ],
    "Expected Columns": [
        59,
        16
    ],
    "Actual Columns": [
        master_export_df.shape[1],
        ml_export_df.shape[1]
    ]
})

sheet_structure_verification["Row Count Difference"] = (
    sheet_structure_verification["Actual Rows"]
    - sheet_structure_verification["Expected Rows"]
)

sheet_structure_verification["Column Count Difference"] = (
    sheet_structure_verification["Actual Columns"]
    - sheet_structure_verification["Expected Columns"]
)

display(sheet_structure_verification)

if master_export_df.shape != (180519, 59):
    raise ValueError(
        f"Master Business exported structure mismatch: {master_export_df.shape}"
    )

if ml_export_df.shape != (180519, 16):
    raise ValueError(
        f"ML Analytics exported structure mismatch: {ml_export_df.shape}"
    )

print("\nEXPORTED COLUMN ORDER VERIFICATION")
print("-" * 80)

master_column_order_match = (
    master_export_df.columns.tolist()
    == master_business_columns
)

ml_column_order_match = (
    ml_export_df.columns.tolist()
    == ml_analytics_columns
)

column_order_verification = pd.DataFrame({
    "Workbook Sheet": [
        "Logistic_Master_Business_Data",
        "Logistic_ML_Analytics_Ready"
    ],
    "Expected Columns": [
        len(master_business_columns),
        len(ml_analytics_columns)
    ],
    "Actual Columns": [
        len(master_export_df.columns),
        len(ml_export_df.columns)
    ],
    "Professional Column Order Status": [
        "PASS" if master_column_order_match else "FAIL",
        "PASS" if ml_column_order_match else "FAIL"
    ]
})

display(column_order_verification)

if not master_column_order_match:
    raise ValueError(
        "Master Business exported column order does not match the approved order."
    )

if not ml_column_order_match:
    raise ValueError(
        "ML Analytics exported column order does not match the approved order."
    )

print("\nRELATIONAL KEY POST-EXPORT VERIFICATION")
print("-" * 80)

relational_key_export_verification = pd.DataFrame({
    "Verification Check": [
        "Primary Relational Key",
        "Key Present in Master Business Export",
        "Key Present in ML Analytics Export",
        "Master Business Missing Key Values",
        "ML Analytics Missing Key Values",
        "Master Business Duplicate Key Values",
        "ML Analytics Duplicate Key Values",
        "Master and ML Key Sequence Match"
    ],
    "Result": [
        "Order Item Id",
        "YES" if "Order Item Id" in master_export_df.columns else "NO",
        "YES" if "Order Item Id" in ml_export_df.columns else "NO",
        master_export_df["Order Item Id"].isna().sum(),
        ml_export_df["Order Item Id"].isna().sum(),
        master_export_df["Order Item Id"].duplicated().sum(),
        ml_export_df["Order Item Id"].duplicated().sum(),
        "PASS" if master_export_df["Order Item Id"].equals(
            ml_export_df["Order Item Id"]
        ) else "FAIL"
    ]
})

display(relational_key_export_verification)

if "Order Item Id" not in master_export_df.columns:
    raise ValueError("Order Item Id missing from Master Business export.")

if "Order Item Id" not in ml_export_df.columns:
    raise ValueError("Order Item Id missing from ML Analytics export.")

if master_export_df["Order Item Id"].isna().sum() != 0:
    raise ValueError("Missing relational keys found in Master Business export.")

if ml_export_df["Order Item Id"].isna().sum() != 0:
    raise ValueError("Missing relational keys found in ML Analytics export.")

if master_export_df["Order Item Id"].duplicated().sum() != 0:
    raise ValueError("Duplicate relational keys found in Master Business export.")

if ml_export_df["Order Item Id"].duplicated().sum() != 0:
    raise ValueError("Duplicate relational keys found in ML Analytics export.")

if not master_export_df["Order Item Id"].equals(
    ml_export_df["Order Item Id"]
):
    raise ValueError(
        "Order Item Id sequence mismatch between exported workbook sheets."
    )

print("\nORIGINAL LOCKED DATASET PRESERVATION VERIFICATION")
print("-" * 80)

original_dataset_verification = pd.DataFrame({
    "Verification Check": [
        "Expected STEP 17 Locked Rows",
        "Current Original Dataset Rows",
        "Expected STEP 17 Locked Columns",
        "Current Original Dataset Columns",
        "Original Dataset Row Structure",
        "Original Dataset Column Structure"
    ],
    "Result": [
        180519,
        df.shape[0],
        70,
        df.shape[1],
        "PASS" if df.shape[0] == 180519 else "FAIL",
        "PASS" if df.shape[1] == 70 else "FAIL"
    ]
})

display(original_dataset_verification)

if df.shape[0] != 180519:
    raise ValueError("Original locked dataset row structure changed.")

if df.shape[1] != 70:
    raise ValueError("Original locked dataset column structure changed.")

print("\nFINAL POST-EXPORT WORKBOOK INTEGRITY STATUS")
print("-" * 80)

final_integrity_verification = pd.DataFrame({
    "Verification Area": [
        "Workbook File Availability",
        "Workbook Sheet Architecture",
        "Master Business Sheet Structure",
        "ML Analytics Sheet Structure",
        "Master Business Column Order",
        "ML Analytics Column Order",
        "Master Business Relational Key Integrity",
        "ML Analytics Relational Key Integrity",
        "Cross-Sheet Relational Key Alignment",
        "Original STEP 17 Dataset Preservation"
    ],
    "Status": [
        "PASS",
        "PASS",
        "PASS",
        "PASS",
        "PASS",
        "PASS",
        "PASS",
        "PASS",
        "PASS",
        "PASS"
    ]
})

display(final_integrity_verification)

print("\nSTEP 18.6 POST-EXPORT VERIFICATION STATUS")
print("-" * 80)
print("Overall Status: PASS")

print("\nSTATUS")
print("-" * 80)
print("STEP 18.6 post-export Excel workbook data integrity verification completed successfully.")
print("Both workbook sheets match the approved architecture.")
print("Both exported sheets preserve all 180519 rows.")
print("Master Business Data preserves exactly 59 approved columns.")
print("ML Analytics Ready preserves exactly 16 approved columns.")
print("Professional column ordering is preserved in both sheets.")
print("Order Item Id remains valid in both workbook sheets.")
print("No missing relational key values were detected.")
print("No duplicate relational key values were detected.")
print("Cross-sheet relational key alignment is preserved.")
print("The original STEP 17 locked dataset remains unchanged.")
print("No rows were removed.")
print("No data values were modified.")
print("The exported workbook has passed final post-export data integrity verification.")

STEP 18.6 — POST-EXPORT EXCEL WORKBOOK DATA INTEGRITY VERIFICATION

WORKBOOK FILE AVAILABILITY VERIFICATION
--------------------------------------------------------------------------------
Workbook File: Logistic_Data_Analyst_Professional_Workbook_Week2.xlsx
Workbook File Available: YES

EXACT WORKBOOK SHEET ARCHITECTURE VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Expected Workbook Sheets,"Logistic_Master_Business_Data, Logistic_ML_Ana..."
1,Actual Workbook Sheets,"Logistic_Master_Business_Data, Logistic_ML_Ana..."
2,Expected Sheet Count,2
3,Actual Sheet Count,2
4,Exact Sheet Architecture Match,PASS



POST-EXPORT SHEET STRUCTURE VERIFICATION
--------------------------------------------------------------------------------


,Workbook Sheet,Expected Rows,Actual Rows,Expected Columns,Actual Columns,Row Count Difference,Column Count Difference
0,Logistic_Master_Business_Data,180519,180519,59,59,0,0
1,Logistic_ML_Analytics_Ready,180519,180519,16,16,0,0



EXPORTED COLUMN ORDER VERIFICATION
--------------------------------------------------------------------------------


,Workbook Sheet,Expected Columns,Actual Columns,Professional Column Order Status
0,Logistic_Master_Business_Data,59,59,PASS
1,Logistic_ML_Analytics_Ready,16,16,PASS



RELATIONAL KEY POST-EXPORT VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Primary Relational Key,Order Item Id
1,Key Present in Master Business Export,YES
2,Key Present in ML Analytics Export,YES
3,Master Business Missing Key Values,0
4,ML Analytics Missing Key Values,0
5,Master Business Duplicate Key Values,0
6,ML Analytics Duplicate Key Values,0
7,Master and ML Key Sequence Match,PASS



ORIGINAL LOCKED DATASET PRESERVATION VERIFICATION
--------------------------------------------------------------------------------


,Verification Check,Result
0,Expected STEP 17 Locked Rows,180519
1,Current Original Dataset Rows,180519
2,Expected STEP 17 Locked Columns,70
3,Current Original Dataset Columns,70
4,Original Dataset Row Structure,PASS
5,Original Dataset Column Structure,PASS



FINAL POST-EXPORT WORKBOOK INTEGRITY STATUS
--------------------------------------------------------------------------------


,Verification Area,Status
0,Workbook File Availability,PASS
1,Workbook Sheet Architecture,PASS
2,Master Business Sheet Structure,PASS
3,ML Analytics Sheet Structure,PASS
4,Master Business Column Order,PASS
5,ML Analytics Column Order,PASS
6,Master Business Relational Key Integrity,PASS
7,ML Analytics Relational Key Integrity,PASS
8,Cross-Sheet Relational Key Alignment,PASS
9,Original STEP 17 Dataset Preservation,PASS



STEP 18.6 POST-EXPORT VERIFICATION STATUS
--------------------------------------------------------------------------------
Overall Status: PASS

STATUS
--------------------------------------------------------------------------------
STEP 18.6 post-export Excel workbook data integrity verification completed successfully.
Both workbook sheets match the approved architecture.
Both exported sheets preserve all 180519 rows.
Master Business Data preserves exactly 59 approved columns.
ML Analytics Ready preserves exactly 16 approved columns.
Professional column ordering is preserved in both sheets.
Order Item Id remains valid in both workbook sheets.
No missing relational key values were detected.
No duplicate relational key values were detected.
Cross-sheet relational key alignment is preserved.
The original STEP 17 locked dataset remains unchanged.
No rows were removed.
No data values were modified.
The exported workbook has passed final post-export data integrity verification.


# Final Summary

This notebook completed the controlled Week 2 Feature Engineering and professional Excel workbook architecture process for the logistics dataset.

## Feature Engineering Completion

The cleaned logistics dataset was processed through the approved Feature Engineering workflow.

A total of 15 approved engineered features were successfully created and verified:

- Delivery_Time_Hours
- Promised_Time_Hours
- Delay_Hours
- Delay_Flag
- Performance_Category
- Delay_Severity_Level
- Order_Year
- Order_Month
- Order_Month_Name
- Order_Day_of_Week
- Is_Weekend_Order
- Is_Commercial_Loss
- Logistics_Corridor_ID
- Shipping_Lane_ID
- Is_Cross_Border

Feature Engineering verification confirmed:

- 180519 dataset rows preserved
- Original 55 cleaned dataset columns preserved
- 15 engineered features successfully added
- Final dataset structure maintained at 70 columns
- No rows removed during Feature Engineering
- No existing cleaned dataset columns removed
- No duplicate column names detected
- No missing values across approved engineered features
- No infinite values detected in numerical engineered features

The Feature Engineering dataset was successfully verified and locked.

## Professional Excel Workbook Architecture

The 70-column Feature Engineering dataset was then organized into a professional two-sheet workbook structure.

### Logistic_Master_Business_Data

This sheet contains:

- 180519 rows
- 59 professionally ordered business, customer, product, commercial, operational and logistics columns
- Order Item Id preserved as the primary relational key

### Logistic_ML_Analytics_Ready

This sheet contains:

- 180519 rows
- 16 professionally ordered analytics and machine learning ready columns
- Order Item Id preserved as the common relational key

The approved workbook architecture successfully preserved the relational connection between both sheets.

## Final Workbook Verification

The exported workbook passed post-export data integrity verification.

Verification confirmed:

- Exact two-sheet workbook architecture
- 180519 rows preserved in both sheets
- Master Business sheet contains exactly 59 approved columns
- ML Analytics Ready sheet contains exactly 16 approved columns
- Professional column ordering preserved
- No missing Order Item Id values
- No duplicate Order Item Id values
- Cross-sheet relational key sequence alignment preserved
- Original 70-column Feature Engineering dataset remains unchanged
- No rows were removed
- No data values were modified

Overall workbook data integrity status: PASS.

# Final Conclusions and Completion Status

The Week 2 Feature Engineering and professional workbook architecture workflow was completed successfully.

The logistics dataset progressed from the cleaned dataset structure into a verified Feature Engineering dataset containing 15 approved analytical features. The dataset structure was preserved throughout the process, with 180519 rows maintained and the final Feature Engineering dataset locked at 70 columns.

The final dataset was then professionally distributed into two approved Excel workbook sheets:

1. Logistic_Master_Business_Data
2. Logistic_ML_Analytics_Ready

The workbook architecture was implemented using Order Item Id as the common relational key between both sheets.

All professional column allocations and column orders were verified before workbook creation. The final exported workbook also passed post-export data integrity verification.

Final verification confirmed:

- Feature Engineering: COMPLETE AND LOCKED
- Engineered Features: 15 of 15 VERIFIED
- Dataset Rows: 180519 PRESERVED
- Feature Engineering Dataset Columns: 70 PRESERVED
- Master Business Sheet: 59 columns VERIFIED
- ML Analytics Ready Sheet: 16 columns VERIFIED
- Workbook Sheet Architecture: PASS
- Relational Key Integrity: PASS
- Cross-Sheet Key Alignment: PASS
- Professional Column Ordering: PASS
- Post-Export Data Integrity: PASS
- Original Locked Dataset Preservation: PASS

The Week 2 notebook workflow has been completed without removing rows, modifying verified source data values, or altering the locked Feature Engineering dataset structure.

The final professional Excel workbook is successfully created and verified for further analysis and subsequent internship work.

## Final Status

WEEK 2 FEATURE ENGINEERING AND WORKBOOK ARCHITECTURE: COMPLETE

OVERALL VERIFICATION STATUS: PASS